

CREATE TABLE stops (
  stop_id varchar(10),
  stop_name varchar(100),
  PRIMARY KEY(stop_id)
);

insert into stops values('BUS466W','22nd St & JR Hiatt Dr (NW Corner): BUS466W');
insert into stops values('BUS304','Blackbird Farms 2 on McCormick Rd: BUS304');
insert into stops values('BUS173','SR 26 & Scarlett Dr (SW Corner): BUS173');
insert into stops values('BUS176','Klondike Rd & SR 26: BUS176');
insert into stops values('BUS902','Blueberry Ln & Klondike Rd (NW Corner): BUS902');
insert into stops values('BUS175','Klondike Rd & E Pine Ave: BUS175');
insert into stops values('BUS572','Georgetown Rd & Klondike Rd (NW Corner): BUS572');
insert into stops values('BUS903','Rosewood Dr & Klondike Rd (NW Corner): BUS903');
insert into stops values('BUS755','Airport Rd & Halsey Dr (SW Corner) BUS755');
insert into stops values('BUS289','Jischke Dr & 3rd St (SE Corner): BUS289');
insert into stops values('BUS584NE','1st St & Jischke Dr (NE Corner): BUS584NE');
insert into stops values('BUS417SE','Airport Rd & Nimitz Dr (SE Corner): BUS417SE');
insert into stops values('BUS754','Airport Rd & Halsey Dr (SE Corner): BUS754');
insert into stops values('BUS146','Aviation Technology Bldg: BUS146');
insert into stops values('BUS415','Purdue Airport Main Terminal: BUS415');
insert into stops values('BUS134','Howarth Center: BUS134');
insert into stops values('BUS887','Chilton Park on Chilton Dr (S Roundabout):BUS887');
insert into stops values('BUS889','Concord Rd & Marcasite Dr (NW Corner): BUS889');
insert into stops values('BUS425S','Wabash Landing on Brown St: BUS425S');
insert into stops values('BUS352','Harrison St & Martin Jischke Dr (NE Corner):BUS352');
insert into stops values('BUS269','Harrison St & University St (NE Corner): BUS269');
insert into stops values('TEMP17','Harrison St & Sheetz St (NE Corner): TEMP17');
insert into stops values('BUS509SE','Tower Dr & Jischke Dr (SE Corner): BUS509SE');
insert into stops values('BUS346','State St & McCutcheon Dr (West of): BUS346');
insert into stops values('BUS543NE','Gates Rd & Nimitz Dr (NE Corner): BUS543NE');
insert into stops values('BUS900','Discovery Learning Center: BUS900');
insert into stops values('BUS899','Morgan & Jischke Dr (NW Corner): BUS899');
insert into stops values('BUS891','Paramount Dr and Pacific Dr (SE Corner): BUS891');
insert into stops values('BUS294','Grant Street Station Apts (at Shelter): BUS294');
insert into stops values('BUS290','Williams St & Grant St (NE Corner): BUS290');
insert into stops values('BUS522','Williams St & Salisbury St (NW Corner): BUS522');
insert into stops values('BUS186','River Rd & Williams St (NW Corner): BUS186');
insert into stops values('BUS489','River Rd & Wood St (SW Corner): BUS489');
insert into stops values('BUS371','Main St & 4th St (NE Corner): BUS371');
insert into stops values('BUS364','Main St & 5th St (NE Corner): BUS364');
insert into stops values('BUS350','Main St & 6th St (NE Corner): BUS350');
insert into stops values('BUS349','Main St & 8th St (NE Corner): BUS349');
insert into stops values('BUS266','9th St & Ferry St (NW Corner): BUS266');
insert into stops values('BUS509SW','Jischke Dr & Tower Dr (SW Corner): BUS509SW');
insert into stops values('BUS472S','Hilltop Dr & Tower Dr (SE Corner): BUS472S');
insert into stops values('BUS562S','Theta Chi on Tower Dr (South): BUS562S');
insert into stops values('BUS554W','Alpha Chi on David Ross Rd (West): BUS554W');
insert into stops values('BUS546N','14th St & Hartford St (NW Corner): BUS546N');
insert into stops values('BUS786','St Anthony Health Care: BUS786');
insert into stops values('BUS787','14th St & Howell St (NW Corner): BUS787');
insert into stops values('BUS508SW','14th St & Greenbush St (South of): BUS508SW');
insert into stops values('BUS348','15th St & Greenbush St (NW Corner): BUS348');
insert into stops values('BUS862','Ball St & 15th St (NW Corner): BUS862');
insert into stops values('BUS861','Hart St & 15th St (NW Corner): BUS861');
insert into stops values('BUS860','Barbee St & Schuyler Ave (at Shelter): BUS860');
insert into stops values('BUS859','Star Lanes on Schuyler Ave: BUS859');
insert into stops values('BUS858','Schuyler Ave & 18th St (NE Corner): BUS858');
insert into stops values('BUS227','Schuyler Ave & 20th St (NE Corner): BUS227');
insert into stops values('BUS863','21st St & Schuyler Ave (NE Corner): BUS863');
insert into stops values('BUS246','24th St & Schuyler Ave (South of): BUS246');
insert into stops values('BUS854','Albany St & 24th St (SE Corner): BUS854');
insert into stops values('BUS353','24th St & Underwood St (North of): BUS353');
insert into stops values('BUS937','22nd St & Underwood St (SW Corner): BUS937');
insert into stops values('BUS274','Underwood St & 20th St (SE Corner): BUS274');
insert into stops values('BUS852','Perrine St & 20th St (SE Corner): BUS852');
insert into stops values('BUS851','Meharry St & 20th St (SE Corner): BUS851');
insert into stops values('BUS850','Wabash Center on 20th St (at Shelter): BUS850');
insert into stops values('BUS452','17th St & Greenbush St (SE Corner): BUS452');
insert into stops values('BUS849','17th St & Howell St (SE Corner): BUS849');
insert into stops values('BUS451','Riggs Community Health Clinic (at Shelter): BUS451');
insert into stops values('BUS488','17th St & Tippecanoe St (SW Corner): BUS488');
insert into stops values('BUS847','Tippecanoe & 14th St (East of): BUS847');
insert into stops values('BUS546W','Hartford St & 14th St (at Shelter): BUS546W');
insert into stops values('BUS789SW','Hartford St & 12th St (SW Corner): BUS789SW');
insert into stops values('BUS417SW','Airport Rd & Nimitz Dr (SW Corner): BUS417SW');
insert into stops values('BUS491W','McCutcheon Hall on McCutcheon: BUS491W');
insert into stops values('BUS107','Jischke Dr & 3rd St (NE Corner): BUS107');
insert into stops values('BUS064','University Hall: BUS064');
insert into stops values('BUS470','Hillenbrand Hall on 3rd St (South): BUS470');
insert into stops values('BUS491E','McCutcheon Hall on McCutcheon (@Shelter): BUS491E');
insert into stops values('BUS417NE','Airport Rd & Nimitz Dr (NE Corner): BUS417NE');
insert into stops values('BUS483N','Marshall Dr & Nimitz Dr (NE Corner): BUS483N');
insert into stops values('BUS272N','Halsey Dr & Nimitz Dr (NE Corner): BUS272N');
insert into stops values('BUS319N','Arnold Dr & Nimitz Dr (NE Corner): BUS319N');
insert into stops values('BUS217','Purdue Village Bldg 142 (at Shelter): BUS217');
insert into stops values('BUS501','McCormick Rd & Third St : BUS501');
insert into stops values('BUS251W','McCormick Rd & Stadium Ave (NW Corner): BUS251W');
insert into stops values('BUS906W','Schwartz Tennis Cntr on McCormick (West): BUS906W');
insert into stops values('BUS394','SW Blackbird Farms Apt Buildings (W): BUS394');
insert into stops values('BUS320','Grant St & Wood St (SE Corner): BUS320');
insert into stops values('BUS598','Harrison St & Grant St (SW Corner): BUS598');
insert into stops values('BUS324','Lynn Hall on Harrison St: BUS324');
insert into stops values('BUS440','Harrison St and S Russell St (SW Corner): BUS440');
insert into stops values('BUS543SE','Gates Rd & Nimitz Dr (SE Corner): BUS543SE');
insert into stops values('BUS249','Discovery Parking Lot (at Shelter): BUS249');
insert into stops values('BUS402','Littleton St & Wiggins St: BUS402');
insert into stops values('BUS530N','Stadium Ave & Garfield St: BUS530N');
insert into stops values('BUS634','Stadium Ave & Grant St (NE Corner): BUS634');
insert into stops values('BUS647','Stadium Ave & Vine St (NE Corner): BUS647');
insert into stops values('BUS291NW','Salisbury St & Stadium Ave (NW Corner): BUS291NW');
insert into stops values('BUS636NW','Salisbury St & Dehart St (NW Corner): BUS636NW');
insert into stops values('BUS333NW','Salisbury St & Meridian St (NW Corner): BUS333NW');
insert into stops values('BUS224','Salisbury St & Leslie Ave (NW Corner): BUS224');
insert into stops values('BUS637NW','Salisbury St & Rockland Dr (NW Corner): BUS637NW');
insert into stops values('BUS582','Salisbury St & Grant St (South of): BUS582');
insert into stops values('BUS924','Salisbury St & Riley Ln (South of): BUS924');
insert into stops values('BUS365NW','Salisbury St & Lindberg Rd (NW Corner): BUS365NW');
insert into stops values('BUS633NW','Salisbury St & Sycamore Ln (NW Corner): BUS633NW');
insert into stops values('BUS293','Salisbury St & Navajo St (at Shelter): BUS293');
insert into stops values('BUS149','Salisbury St & Kent Ave (at Shelter): BUS149');
insert into stops values('BUS130','Westminster Village at Westminster Dr & Salisbury St (NW Corner): BUS130');
insert into stops values('BUS131W','Westminster Village at Westminster Cir & Salisbury St (NW Corner): BUS131W');
insert into stops values('BUS138','Cumberland Ave & Salisbury St (SW Corner): BUS138');
insert into stops values('BUS133','Cumberland Pointe on Cumberland Ave(South): BUS133');
insert into stops values('BUS136','Cumberland Ave & Manchester St (SW Corner): BUS136');
insert into stops values('BUS964','Cumberland Ave & Yeager Rd (SW Corner): BUS964');
insert into stops values('BUS455S','Salem Courthouse on Cumberland Ave (South of): BUS455S');
insert into stops values('BUS511SW','Cumberland Ave & Kent Ave (South West of):BUS511SW');
insert into stops values('BUS922','Christina & Co Cumberland Ave (SE Corner): BUS922');
insert into stops values('BUS165','3rd St & Alabama St (SE Corner): BUS165');
insert into stops values('BUS991','South Tipp Park: BUS991');
insert into stops values('BUS310','Washington Ave & Kossuth St (SE Corner): BUS310');
insert into stops values('BUS657','Holloway Dr & Washington St (SE Corner): BUS657');
insert into stops values('BUS424','Holloway Dr & Owen St (North of): BUS424');
insert into stops values('BUS979','Owen St & 4th St (West of): BUS979');
insert into stops values('BUS264E','4th St & Montefiore St (SE Corner): BUS264E');
insert into stops values('BUS148','4th St & Thise Ct (SE Corner): BUS148');
insert into stops values('BUS910','Valley Plaza on 4th St (South Driveway): BUS910');
insert into stops values('BUS653SW','Old US 231S & Windy Hill Dr (South Side): BUS653SW');
insert into stops values('BUS258','Old US 231S & Elston Rd: BUS258');
insert into stops values('BUS976','Elston Rd & Breckenridge St (SW of): BUS976');
insert into stops values('BUS975','Elston Rd &  S Beck Ln (SW Corner): BUS975');
insert into stops values('BUS974','Old Romney Rd & Elston Rd (SE Corner): BUS974');
insert into stops values('BUS208','Old Romney Rd & US52 / SR 25 (South of): BUS208');
insert into stops values('BUS222','Twyckenham Blvd & Old Romney Rd (NE Corner):BUS222');
insert into stops values('BUS239','Twyckenham Blvd & CR 10W (North): BUS239');
insert into stops values('BUS343','McDonalds on Old 231: BUS343');
insert into stops values('BUS336','Pay Less on Beck Ln: BUS336');
insert into stops values('BUS700','Beck Ln & Limestone Ln (NE Corner): BUS700');
insert into stops values('BUS702','Poland Hill Rd & Matterhorn Pl (SE Corner): BUS702');
insert into stops values('BUS704N','Twyckenham Blvd & Rampart St (NE Corner): BUS704N');
insert into stops values('BUS340N','Twyckenham Blvd & 9th St (NW Corner): BUS340N');
insert into stops values('BUS338','Twyckenham Blvd & 18th St (NW Corner): BUS338');
insert into stops values('BUS990','18th St at RRX (at Trailhead): BUS990');
insert into stops values('BUS884','18th St & Summertime Tr (SE Corner): BUS884');
insert into stops values('BUS883','18th St & Bridgewater Cir (SE Corner): BUS883');
insert into stops values('BUS917','18th St & Troxel Ct: BUS917');
insert into stops values('BUS875NE','Veterans Mem Pkwy S & Regal Valley Dr: BUS875NE');
insert into stops values('BUS881','Veterans Mem Pkwy S & IFCU Dr (West of): BUS881');
insert into stops values('BUS880','Veterans Mem Pkwy S & Cheryl Ln (West of) : BUS880');
insert into stops values('BUS927NW','Broadview Rd & Soldiers Home(NW Corner): BUS927NW');
insert into stops values('BUS928NE','Veterans Home Entrance (North Side): BUS928NE');
insert into stops values('BUS933','Ingersol Hall at Indiana Veterans Home: BUS933');
insert into stops values('BUS932','Pyle Hall at Indiana Veterans Home: BUS932');
insert into stops values('BUS931','Mitchell Hall at Indiana Veterans Home: BUS931');
insert into stops values('BUS930','Dehart Hall at Indiana Veterans Home: BUS930');
insert into stops values('BUS929','Lincoln Hall at Indiana Veterans Home: BUS929');
insert into stops values('BUS928SE','Veterans Home Entrance on Soldiers Home: BUS928SE');
insert into stops values('BUS927SE','Broadview Rd & Soldiers Home(SE Corner): BUS927SE');
insert into stops values('BUS616','Heritage Health Care on Soldiers Home Rd: BUS616');
insert into stops values('BUS936NE','Soldiers Home & Overlook Dr (NE Corner): BUS936NE');
insert into stops values('BUS613','Hartman Ct & Soldiers Home Rd (SE Corner): BUS613');
insert into stops values('BUS926','Soldiers Home Rd & Myrtle Dr (NW of): BUS926');
insert into stops values('BUS335','Soldiers Home Rd & Sharon Rd (NE Corner): BUS335');
insert into stops values('BUS595E','Parkway Apts on Happy Hollow: BUS595E');
insert into stops values('BUS361SE','Happy Hollow Rd & Chippewa St (SE Corner): BUS361SE');
insert into stops values('BUS597E','Pathway Ln & Happy Hollow Rd (SE Corner): BUS597E');
insert into stops values('BUS123E','Nobb Hill Apts on Happy Hollow Rd: BUS123E');
insert into stops values('BUS600N','Happy Hollow Rd & Catherwood Dr(NE Corner):BUS600N');
insert into stops values('BUS145E','Launch Apts (North Drive): BUS065');
insert into stops values('BUS460','Launch Apts (South Drive, SE Corner): BUS460');
insert into stops values('BUS602E','River Rd & Robinson St (North of, East): BUS602E');
insert into stops values('BUS951','Salisbury St & Wiggins St (SW Corner): BUS951');
insert into stops values('BUS950','Wiggins St & Vine St (SW Corner): BUS950');
insert into stops values('BUS559','Northwestern Ave & Wiggins St (NW of): BUS559');
insert into stops values('BUS223','Lodge Apts on Cumberland Ave (at Shelter): BUS223');
insert into stops values('BUS511NW','Cumberland Ave & Kent Ave (North West of):BUS511NW');
insert into stops values('BUS455N','Salem Courthouse Apts (at Shelter): BUS455N');
insert into stops values('BUS218NE','Cumberland Ave & Yeager Rd (East of): BUS218NE');
insert into stops values('BUS541','Cumberland Ave & Browning St (NE Corner): BUS541');
insert into stops values('BUS594','Cumberland Pointe on Cumberland(NE Corner):BUS594');
insert into stops values('BUS418','Cumberland Ave & Salisbury St (West of): BUS418');
insert into stops values('BUS427','Westminster Village N & Salisbury (East): BUS427');
insert into stops values('BUS610','Salisbury St. and Kent Ave (north of): BUS610');
insert into stops values('BUS484','Park Ridge Dr & Salisbury St (SE Corner): BUS484');
insert into stops values('BUS633SE','Salisbury St & Sycamore Ln (SE Corner): BUS633SE');
insert into stops values('BUS365SE','Salisbury St & Lindberg Rd (SE Corner): BUS365SE');
insert into stops values('BUS638','Salisbury St & Creighton Rd (NE Corner): BUS638');
insert into stops values('BUS337NE','Salisbury St & Grant St (NE Corner): BUS337NE');
insert into stops values('BUS637SE','Salisbury St & Rockland Dr (SE Corner): BUS637SE');
insert into stops values('BUS493','Happy Hollow School on Salisbury(SE Corner):BUS493');
insert into stops values('BUS333SE','Salisbury St & Robinson St (SE Corner): BUS333SE');
insert into stops values('BUS636SE','Salisbury St & Dehart St (SE Corner): BUS636SE');
insert into stops values('BUS061','Stadium Ave & Salisbury St (SW Corner): BUS061');
insert into stops values('BUS635','Stadium Ave & Vine St (SW Corner): BUS635');
insert into stops values('BUS622','Dodge St & Grant St (SW Corner): BUS622');
insert into stops values('BUS530S','Dodge St & Garfield St (SW Corner): BUS530S');
insert into stops values('BUS530','Northwestern Ave & Stadium Ave (McDonalds): BUS530');
insert into stops values('BUS949','W Fowler Ave & Vine St (NW Corner): BUS949');
insert into stops values('BUS359','E Fowler Ave & Littleton St (NW Corner): BUS359');
insert into stops values('BUS519W','Fannon & Salem St (NW Corner): BUS519W');
insert into stops values('BUS564','4th St & Wall St (SE Corner): BUS564');
insert into stops values('BUS580','River Rd & Howard Ave (SW of Corner): BUS580');
insert into stops values('BUS124','River Rd & Quincy St (at Shelter): BUS124');
insert into stops values('BUS602W','River Rd & Robinson St (NW Corner): BUS602W');
insert into stops values('BUS066','Launch Apts (North, @Shelter): BUS066');
insert into stops values('BUS600E','Catherwood Dr & Happy Hollow Rd (East of): BUS600E');
insert into stops values('BUS123W','Nobb Hill Apts on Happy Hollow Rd (at Shelter): BUS123W');
insert into stops values('BUS599W','Happy Hollow Rd & Laurel Dr (SW Corner): BUS599W');
insert into stops values('BUS597W','Happy Hollow Rd & Pathway Ln (SW Corner): BUS597W');
insert into stops values('BUS596','Happy Hollow Rd & Knox Dr (NW Corner): BUS596');
insert into stops values('BUS361NW','Happy Hollow Rd & Chippewa St (NW Corner): BUS361NW');
insert into stops values('BUS595W','Parkway Apts on Happy Hollow: BUS595W');
insert into stops values('BUS144','Univ Crossing Apts Soldiers Home (@Shelter) :BUS144');
insert into stops values('BUS959','Soldiers Home Rd & Linda Ln: BUS959');
insert into stops values('BUS267','Soldiers Home Rd & Cumberland (NW Corner): BUS267');
insert into stops values('BUS824','Soldiers Home Rd & Prophet Dr (SW of): BUS824');
insert into stops values('BUS692','South St & Main St (NE Corner): BUS692');
insert into stops values('BUS691','South St & 19th St (NE Corner): BUS691');
insert into stops values('BUS690','South St & 23rd St (NE Corner): BUS690');
insert into stops values('BUS669','McCarty Ln & Sagamore Pkwy S (East of): BUS669');
insert into stops values('BUS660','McCarty Ln & Industrial Dr (NE Corner): BUS660');
insert into stops values('BUS656','McCarty Ln & Kepner Dr (NE Corner): BUS656');
insert into stops values('BUS651','McCarty Ln & Landmark Dr (NE Corner): BUS651');
insert into stops values('BUS650','McCarty Ln & Sickle Ct (NW Corner): BUS650');
insert into stops values('BUS819','McCarty Ln & Park East Blvd (NE Corner): BUS819');
insert into stops values('BUS894','Lark West Lafayette: BUS894');
insert into stops values('BUS521','Beck Ln & Davis Dr (SW Corner): BUS521');
insert into stops values('BUS537','Beck Ln & 9th St (East of): BUS537');
insert into stops values('BUS679','Bishop Woods on 9th St (West Side): BUS679');
insert into stops values('BUS693','9th St & Sarasota Dr (SW Corner): BUS693');
insert into stops values('BUS316','9th St & Rosemont St (NW Corner): BUS316');
insert into stops values('BUS515','Teal Rd & Crestview Ct (NE Corner): BUS515');
insert into stops values('BUS494','Fairgrounds on Teal Rd (Teal Rd Entrance): BUS494');
insert into stops values('BUS187NW','18th St & Teal Rd (West of): BUS187NW');
insert into stops values('BUS815','18th St & JR Hiatt (SW Corner): BUS815');
insert into stops values('BUS986S','Logan Ave & 18th St (SW Corner): BUS986S');
insert into stops values('BUS327SW','Logan Ave & El Prado Ave (SW Corner): BUS327SW');
insert into stops values('BUS857','14th St & Logan Ave (NW Corner): BUS857');
insert into stops values('BUS303','14th St & King St (NW Corner): BUS303');
insert into stops values('BUS182','14th St & Central Ave (NW Corner): BUS182');
insert into stops values('BUS210','14th St & Adams St (NW Corner): BUS210');
insert into stops values('BUS108','Kossuth St & 14th St (SW Corner): BUS108');
insert into stops values('BUS288','Kossuth St & 11th St (SW Corner): BUS288');
insert into stops values('BUS253E','Kossuth St & 9th St (East of): BUS253E');
insert into stops values('BUS683','9th St & Hitt St (NW Corner): BUS683');
insert into stops values('BUS698','Historical Museum on 9th St (West Side): BUS698');
insert into stops values('BUS519E','Salem St & Fannon (NE Corner): BUS519E');
insert into stops values('BUS845','Salem St & 7th (NE Corner): BUS845');
insert into stops values('BUS380NE','Salem St & 9th St (NE Corner): BUS380NE');
insert into stops values('BUS843','11th St & Salem St (NE Corner): BUS843');
insert into stops values('BUS842','Village Pantry on Salem St: BUS842');
insert into stops values('BUS840','Salem St &16th St (West of): BUS840');
insert into stops values('BUS839','18th St & Salem St (North of): BUS839');
insert into stops values('BUS838','Speedway on Elmwood Ave (NE Corner): BUS838');
insert into stops values('BUS873NE','Northend Community Center');
insert into stops values('BUS835','Market Square Shopping Center: BUS835');
insert into stops values('BUS841','Elmwood Avenue & Greenbush St: BUS841');
insert into stops values('BUS830','27th St & Underwood St (South of): BUS830');
insert into stops values('BUS209','Elmwood Ave & Underwood St (SE Corner): BUS209');
insert into stops values('BUS829','Elmwood Ave & Prairie Ln (SE Corner): BUS829');
insert into stops values('BUS276','Vinton St & Elmwood Ave (SE Corner): BUS276');
insert into stops values('BUS827','Elmwood Ave & 27th St (SE Corner): BUS827');
insert into stops values('BUS938','Elmwood Ave & 27th St (West of): BUS938');
insert into stops values('BUS207','Wayne Terrace & Elmwood Ave (SW Corner): BUS207');
insert into stops values('BUS132','Elmwood Ave & Rainbow Dr (SW Corner): BUS132');
insert into stops values('BUS325SE','21st St & Elmwood Ave (SE Corner): BUS325SE');
insert into stops values('BUS825','21st St & Cobblestone Ct: BUS825');
insert into stops values('BUS848','21st St & Union St: BUS848');
insert into stops values('BUS454','Stonecrest Apartments (at Shelter): BUS454');
insert into stops values('BUS441','Union St & 18th St (SW Corner): BUS441');
insert into stops values('BUS822','Union St & 15th St (East of): BUS822');
insert into stops values('BUS401','Union St & 14th St (SW Corner): BUS401');
insert into stops values('BUS821','12th St & Union St (SW Corner): BUS821');
insert into stops values('BUS367E','Union St & 9th St (East of): BUS367E');
insert into stops values('BUS818','8th St & Union St (SW Corner): BUS818');
insert into stops values('BUS745','Cincinnati St & 6th St (SE Corner): BUS745');
insert into stops values('BUS410SE','6th St & Brown St (SW Corner): BUS410SE');
insert into stops values('BUS568','Earhart Hall on First St (North Side) : BUS568');
insert into stops values('BUS584SE','1st St & Jischke Dr (SE Corner): BUS584SE');
insert into stops values('BUS063','Stone Hall on Oval Dr: BUS063');
insert into stops values('BUS435','Class of 1950: BUS435');
insert into stops values('BUS448','Stewart Center: BUS448');
insert into stops values('BUS412','Northwestern Ave & Columbia St (Chauncey Village): BUS412');
insert into stops values('BUS538','Electrical Engineering: BUS538');
insert into stops values('BUS190','Armstrong Hall on Stadium Ave (@Shelter): BUS190');
insert into stops values('BUS735E','Commanche Trl & Shasta Dr (South of): BUS735E');
insert into stops values('BUS449N','Brady Ln & Commanche Trl (NE Corner): BUS449N');
insert into stops values('BUS720','Brady Ln & Portsmouth Dr W (NE Corner): BUS720');
insert into stops values('BUS301N','Pheasant Run Apts on Brady Ln (at Shelter): BUS301N');
insert into stops values('BUS961','Village Pantry on Brady Ln (North Side): BUS961');
insert into stops values('BUS713','Brady Ln East of Reagan Dr (North): BUS713');
insert into stops values('BUS711N','Brady Ln & Imperial Pkwy (NE Corner): BUS711N');
insert into stops values('BUS404NE','Creasy Ln & US 52 (NE Corner): BUS404NE');
insert into stops values('BUS142N','Ivy Tech on Creasy Ln: BUS142N');
insert into stops values('BUS941NW','Creasy Ln & Bonlou (Menards Entrance): BUS941NW');
insert into stops values('BUS719','Torchwood Dr & SR 38 (SW Corner): BUS719');
insert into stops values('BUS437W','PayLess on SR 38 (East of Shelter): BUS437W');
insert into stops values('BUS561','Lambert Fieldhouse on University St: BUS561');
insert into stops values('BUS111','Lambert Fieldhouse on Stadium Ave: BUS111');
insert into stops values('BUS804','Honors College on Russell St: BUS804');
insert into stops values('BUS439','Russell St & 4th St (NW Corner): BUS439');
insert into stops values('BUS213S','Steven Beering Dr & Tower Dr (Southwest of): BUS213S');
insert into stops values('BUS426','Stadium Parking Lot on Victory Dr (at Shelter): BUS426');
insert into stops values('BUS893','Walmart (South Lafayette) (West of Entr): BUS893');
insert into stops values('BUS892','Pink Walrus Yogurt: BUS892');
insert into stops values('BUS877','Promenade Pkwy & Veterans Memorial Pkwy S: BUS877');
insert into stops values('BUS876','Foxfire Apts on Veterans Mem Pkwy S: BUS876');
insert into stops values('BUS875SW','Vet Mem Pkwy S & Regal Valley Dr: BUS875SW');
insert into stops values('BUS874','Valley Lakes Center on Vet Mem Pkwy S: BUS874');
insert into stops values('BUS873','18th St & Waverly Dr (NW Corner): BUS873');
insert into stops values('BUS871','18th St & Ortman Ln (NW Corner): BUS871');
insert into stops values('BUS869','18th St & Normandy Dr (NW Corner): BUS869');
insert into stops values('BUS866','18th St and Twyckenham Blvd: BUS866');
insert into stops values('BUS340S','Twyckenham Blvd & 9th St (SW Corner): BUS340S');
insert into stops values('BUS704S','Twyckenham Blvd & Quarry Dr (SW Corner): BUS704S');
insert into stops values('BUS703S','Poland Hill & Twyckenham Blvd (East of): BUS703S');
insert into stops values('BUS764','Twyckenham Blvd & Old US 231S (East of):BUS764');
insert into stops values('BUS658','CR 10 W & Twyckenham Blvd (SW Corner): BUS658');
insert into stops values('BUS211','Twyckenham Blvd & Old Romney (NW Corner): BUS211');
insert into stops values('BUS212','Romney Meadows Apts (at Shelter): BUS212');
insert into stops values('BUS159','Old Romney Rd & SR 25 (NW Corner): BUS159');
insert into stops values('BUS655','Elston Point Apts on Elston Rd(NE Corner): BUS655');
insert into stops values('BUS270','Elston Rd & Beck Ln (West of): BUS270');
insert into stops values('BUS254','Elston Rd & Old US231 (West of): BUS254');
insert into stops values('BUS653NE','Old US 231S & Windy Hill Dr (North Side): BUS653NE');
insert into stops values('BUS261','4th St & Teal Rd (North of): BUS261');
insert into stops values('BUS665','4th St & Williams Ridge/Saw Mill Rd: BUS665');
insert into stops values('BUS264W','4th St & Montefiore St (NW Corner): BUS264W');
insert into stops values('BUS399','4th St & Owen St (NW Corner): BUS399');
insert into stops values('BUS240','4th St & Fairmont St (NW Corner): BUS240');
insert into stops values('BUS194','Fountain St & 4th St (NW Corner): BUS194');
insert into stops values('BUS150','Alabama St & 4th St (SW Corner): BUS150');
insert into stops values('BUS403','Walmart West Lafayette (at Shelter): BUS403');
insert into stops values('BUS137','Four Points Sheraton on Cumberland Ave: BUS137');
insert into stops values('BUS250','Sagamore Pkwy W & Geddes Way (South of): BUS250');
insert into stops values('BUS390','Sagamore Pkwy W & Morehouse Rd (SW Corner): BUS390');
insert into stops values('BUS179','Alight West Lafayette: BUS179');
insert into stops values('BUS283','Sagamore Pkwy W & Hunter Rd (SW Corner): BUS283');
insert into stops values('BUS170','US 231/52  & Wyndham Way (East of): BUS170');
insert into stops values('BUS342','Klondike Rd & US 52 (SE Corner): BUS342');
insert into stops values('BUS317','Klondike Schools (SE Corner Center Drive): BUS317');
insert into stops values('BUS204','Lafayette Blind on Klondike Rd: BUS204');
insert into stops values('BUS464','Pemberly Cts on Klondike Rd: BUS464');
insert into stops values('BUS268','Klondike Rd & Snowdrop Dr (SE Corner): BUS268');
insert into stops values('BUS195','Lindberg Rd & Klondike Rd (NE Corner): BUS195');
insert into stops values('BUS904','Longspur Dr & Lindberg Rd (NE Corner): BUS904');
insert into stops values('BUS498','Wake Robin Dr & Lindberg Rd (NE Corner): BUS498');
insert into stops values('BUS905','Robin Hood Ln & Lindberg Rd (NE Corner): BUS905');
insert into stops values('BUS308','Village West Apts on Lindberg (at Shelter): BUS308');
insert into stops values('BUS236','McCormick Rd & Lindberg Rd (SE Corner): BUS236');
insert into stops values('BUS393','SW Blackbird Farms Apt Buildings (E): BUS393');
insert into stops values('BUS906E','Schwartz Tennis Cntr on McCormick (East): BUS906E');
insert into stops values('BUS251E','McCormick Rd & Stadium Ave (NE Corner): BUS251E');
insert into stops values('BUS205','Lindberg Rd & Kestral Blvd (NE Corner): BUS205');
insert into stops values('BUS375W','Lindberg Rd & Northwestern Ave (Northwest of): BUS375W');
insert into stops values('BUS897','Northwestern Ave & Windsor DR (SW of): BUS897');
insert into stops values('BUS161','Northwestern Ave & Yeager Rd (NW Corner): BUS161');
insert into stops values('BUS162','Northwestern Ave & Neil Armstrong Dr (NW): BUS162');
insert into stops values('BUS456','Purdue Village Bldgs 149-151: BUS456');
insert into stops values('BUS275','Halsey Dr & Arnold Dr (NW Corner): BUS275');
insert into stops values('BUS262','Nimitz Dr & Halsey Dr (SW Corner): BUS262');
insert into stops values('BUS263','Purdue Village Preschool on Nimitz Dr: BUS263');
insert into stops values('BUS125','Squirrel Park on Nimitz Dr (at Crosswalk): BUS125');
insert into stops values('BUS285','MacArthur Dr & 1st St (NW Corner): BUS285');
insert into stops values('BUS473','Hillenbrand Hall on 3rd St (North): BUS473');
insert into stops values('BUS413','Ford Hall on Stadium (North Side): BUS413');
insert into stops values('BUS154','Young Hall on Grant St (East): BUS154');
insert into stops values('BUS504','McCormick Rd & 3rd Street: BUS504');
insert into stops values('BUS566','Purdue West on State St: BUS566');
insert into stops values('BUS898','First Street Towers on State St: BUS898');
insert into stops values('BUS156','Wabash Landing on State St (at Shelter): BUS156');
insert into stops values('BUS287NE','Columbia St & 2nd St (NE Corner): BUS287NE');
insert into stops values('BUS421SW','SR 38 & Kingsway Dr (SW Corner): BUS421SW');
insert into stops values('BUS948','Professional Ct & SR 38 (SW Corner): BUS948');
insert into stops values('BUS141','SR 38 at Shoe Carnival: BUS141');
insert into stops values('BUS667','Lafayette Marketplace: BUS667');
insert into stops values('BUS525','Main St & McCarty Ln (West of): BUS525');
insert into stops values('BUS531SW','Main St & Earl Ave (SW Corner): BUS531SW');
insert into stops values('BUS664SE','Main St & S 28th St (SE Corner): BUS664SE');
insert into stops values('BUS663SE','Main St & S 25th St (South of): BUS663SE');
insert into stops values('BUS216W','Main St & 24th St (Northwest of): BUS216W');
insert into stops values('BUS947','Main St & Congress St (North of): BUS947');
insert into stops values('BUS482NW','Main St & Scott St (NW Corner): BUS482NW');
insert into stops values('BUS444SW','Main St & Jackson St (SW Corner): BUS444SW');
insert into stops values('BUS391NW','Main St & Alabama St (NW Corner): BUS391NW');
insert into stops values('BUS939','South St & 16th St (SW Corner): BUS939');
insert into stops values('BUS152','River Walk Apartments on 9th St: BUS152');
insert into stops values('BUS367SE','Union St & 9th St (SE Corner): BUS367SE');
insert into stops values('BUS783SE','9th St & Cincinnati St (SE Corner): BUS783SE');
insert into stops values('BUS220SE','9th St & Brown St (SE Corner): BUS220SE');
insert into stops values('BUS255','9th St & Ferry St (Northeast of): BUS255');
insert into stops values('BUS355','Main St & 7th St (SW Corner): BUS355');
insert into stops values('BUS358','Main St & 6th St (SW Corner): BUS358');
insert into stops values('BUS363','Main St & 5th St (SW Corner): BUS363');
insert into stops values('BUS644','Wabash Landing on State St (at Roebuck Dr): BUS644');
insert into stops values('BUS458','River Rd & Wood St (East of): BUS458');
insert into stops values('BUS523','Williams St & Salisbury St (SW Corner): BUS523');
insert into stops values('BUS323','Grant St & Williams St (NW Corner): BUS323');
insert into stops values('BUS322','Grant St & Harrison St (NW Corner): BUS322');
insert into stops values('BUS153','Young Hall on Grant St (West): BUS153');
insert into stops values('BUS345','Lilly Hall on State St (at Shelter): BUS345');
insert into stops values('BUS584NW','Jischke Dr & 1st St (NW Corner): BUS584NW');
insert into stops values('BUS366','Jischke Dr & 3rd St (SW Corner): BUS366');
insert into stops values('BUS282NE','MacArthur Dr & 1st St (at Shelter): BUS282NE');
insert into stops values('BUS673','Dicks at Tippecanoe Mall: BUS673');
insert into stops values('BUS672','Wendys at Tippecanoe Mall (South Side): BUS672');
insert into stops values('BUS376','Cambridge Estates on SR 38: BUS376');
insert into stops values('BUS717','Guaranteed Transmission on SR 38: BUS717');
insert into stops values('BUS499','SR 38 & Creasy Ln (West of): BUS499');
insert into stops values('BUS499N','Creasy Ln & SR 38/25 (North of, West Side): BUS499N');
insert into stops values('BUS915','Creasy Ln & St. Francis Way (NW Corner): BUS915');
insert into stops values('BUS770NW','Creasy Ct & Creasy Ln (NW Corner): BUS770NW');
insert into stops values('BUS769NW','Amelia Ave & Creasy Ln (NW Corner): BUS769NW');
insert into stops values('BUS768','Creasy Ln (Across from Burberry Dr): BUS768');
insert into stops values('BUS774N','Emerald Pines & McCarty Ln (NE Corner): BUS774N');
insert into stops values('BUS766W','McCarty Ln & Sickle Ct (NW Corner): BUS766W');
insert into stops values('BUS765NW','Sickle Ct & Julia Ln (NW Corner): BUS765NW');
insert into stops values('BUS200S','Julia Ln & Harper Dr (SW Corner): BUS200S');
insert into stops values('BUS775SW','Stinger St & Harper Dr (SW Corner): BUS775SW');
insert into stops values('BUS763W','Creasy Ln & Fortune Dr (SE Corner): BUS763E');
insert into stops values('BUS771','Starbucks Coffee on Creasy Ln: BUS771');
insert into stops values('BUS192','Creasy Ln & South St (West Side North of): BUS192');
insert into stops values('BUS468','Rome Dr & Creasy Ln (SW Corner): BUS468');
insert into stops values('BUS896','Executive Dr & Rome Dr (SE Corner): BUS896');
insert into stops values('BUS820','Rome Dr & Shenandoah Dr (at  Shelter): BUS820');
insert into stops values('BUS759W','S Driftwood & Shenandoah Dr (SW Corner) : BUS759W');
insert into stops values('BUS920NW','Claremont Ln & Shenandoah Dr(NW Corner): BUS920NW');
insert into stops values('BUS485','Shenandoah Dr & Union St (NW Corner): BUS485');
insert into stops values('BUS757NW','S Navarre Dr & Shenandoah (NW Corner): BUS757NW');
insert into stops values('BUS050','Shenandoah Drive at Munger Trail Crossing: BUS050');
insert into stops values('BUS513','Shenandoah Dr & Greenbush St (SW Corner): BUS513');
insert into stops values('BUS526SW','Chauncey Ct & Greenbush St (SW Corner): BUS526SW');
insert into stops values('BUS753','RRX on Greenbush St (SW Corner): BUS753');
insert into stops values('BUS231S','Greenbush St & Sagamore Pkwy N (SW Corner):BUS231S');
insert into stops values('BUS453','Greenbush St & 28th St (East of): BUS453');
insert into stops values('BUS278SW','Greenbush St & Elmwood Ave (SW Corner): BUS278SW');
insert into stops values('BUS245SE','Market Square (EAST) on Greenbush St: BUS245SE');
insert into stops values('BUS245SW','Market Square (WEST) on Greenbush St: BUS245SW');
insert into stops values('BUS230S','Greenbush Crossing Apartments: BUS230S');
insert into stops values('BUS330SW','Greenbush St & 18th St (SW Corner): BUS330SW');
insert into stops values('BUS921','Linnwood Park: BUS921');
insert into stops values('BUS512','9th St  & Greenbush St (SE Corner): BUS512');
insert into stops values('BUS987SE','9th St & Roberts St (SE Corner): BUS987SE');
insert into stops values('BUS292SE','9th St & Hartford St (SE Corner): BUS292SE');
insert into stops values('BUS380SE','Salem St & 9th St (SE Corner): BUS380SE');
insert into stops values('BUS328','6th St & Union St (SE Corner): BUS328');
insert into stops values('BUS746','Tippecanoe Co. Health Dept. on 6th St: BUS746');
insert into stops values('BUS410SW','Brown St & 6th St (SW Corner): BUS410SW');
insert into stops values('BUS744','Brown St & 5th St (SW Corner): BUS744');
insert into stops values('BUS547','State St & Russell St (NE Corner): BUS547');
insert into stops values('BUS271','Purdue Memorial Union (PMU) on State St: BUS271');
insert into stops values('BUS557','Physics (pulloff on Northwestern): BUS557');
insert into stops values('BUS300','The Quarters on Lindberg (at Shelter): BUS300');
insert into stops values('BUS010','The Cottages on Lindberg on Mida Dr: BUS010');
insert into stops values('BUS802','Willowbrook Dr & Willowbrook Cr (North of): BUS802');
insert into stops values('BUS801','Village West Clubhouse on Willowbrook Dr: BUS801');
insert into stops values('BUS549N','Fowler House Apts on Ferry St (North): BUS549N');
insert into stops values('BUS534N','Ferry St & 6th St (NE Corner): BUS534N');
insert into stops values('BUS532NE','Ferry St & 8th St (NE Corner): BUS532NE');
insert into stops values('BUS794N','Ferry St & 10th St (North Side): BUS794N');
insert into stops values('BUS796N','Ferry St & Erie St (West of) : BUS796N');
insert into stops values('BUS797N','Ferry St & Perrin Ave (West of): BUS797N');
insert into stops values('BUS798NE','Ferry St & Asher St (NE Corner): BUS798NE');
insert into stops values('BUS280N','Ferry St & 19th St (West of): BUS280N');
insert into stops values('BUS548NE','Ferry St & 21st St (NE Corner): BUS548NE');
insert into stops values('BUS545N','Ferry St & 23rd St (NE Corner): BUS545N');
insert into stops values('BUS542','Ferry St & 26th St (NE Corner at Shelter): BUS542');
insert into stops values('BUS116','Ferry St & 28th St (NW Corner): BUS116');
insert into stops values('BUS487W','Earl Ave & Ferry St (NW Corner): BUS487W');
insert into stops values('BUS459NW','Earl Ave & Cason St (NW Corner): BUS459NW');
insert into stops values('BUS507W','Portledge Commons Apts on Earl Ave: BUS507W');
insert into stops values('BUS196W','Earl Ave & Union St (Southwest of): BUS196W');
insert into stops values('BUS382N','Union St & Sagamore Pkwy N (NW of): BUS382N');
insert into stops values('BUS793','RRX on Union St (NE Corner): BUS793');
insert into stops values('BUS552SE','36th St & Union St (SE Corner): BUS552SE');
insert into stops values('BUS813E','36th St & Coleman Ct (North of): BUS813E');
insert into stops values('BUS411','36th & South St (NE Corner): BUS411');
insert into stops values('BUS811','Target on South St (@ 5th/3rd Bank): BUS811');
insert into stops values('BUS302','South St & Executive Dr (West of): BUS302');
insert into stops values('BUS831','South St & Creasy Ln (West of): BUS831');
insert into stops values('BUS816','South St & Creasy Ln (Southeast of): BUS816');
insert into stops values('BUS806','South St & Eastland Dr (West of): BUS806');
insert into stops values('BUS406','South St & Brinker St (West of): BUS406');
insert into stops values('BUS386','South St & Red Cloud Trl (East of): BUS386');
insert into stops values('BUS277N','SR 26 & Frontage Rd (NE Corner): BUS277N');
insert into stops values('BUS299','Meijer Ct & Meijer Dr (NE Corner): BUS299');
insert into stops values('BUS257','Meijer Store East (at Shelter): BUS257');
insert into stops values('BUS492','Brown St & 4th St (NE Corner): BUS492');
insert into stops values('BUS410NE','Brown St & 6th St (NE Corner): BUS410NE');
insert into stops values('BUS748','Cincinnati St & 7th St (NE Corner): BUS748');
insert into stops values('BUS783NW','9th St & Cincinnati St (NW Corner): BUS783NW');
insert into stops values('BUS367','9th St & Union St (NW Corner): BUS367');
insert into stops values('BUS380NW','Salem St & 9th St (NW Corner): BUS380NW');
insert into stops values('BUS292NW','9th St & Hartford St (NW Corner): BUS292NW');
insert into stops values('BUS987NW','9thSt & Roberts St (NW Corner): BUS987NW');
insert into stops values('BUS960','ZF on 9th St: BUS960');
insert into stops values('BUS422E','Canal Rd & 9th St (1A by Request): BUS422E');
insert into stops values('BUS143','CityBus Offices - Canal Rd (1A by Request): BUS143');
insert into stops values('BUS422W','Canal Rd & 9th St (1A by Request): BUS422W');
insert into stops values('BUS296','Greenbush St & 12th St (Northeast of): BUS296');
insert into stops values('BUS508NE','Greenbush St & 14th St (NE Corner): BUS508NE');
insert into stops values('BUS750','Greenbush St & 16th St (NE Corner): BUS750');
insert into stops values('BUS330NE','Greenbush St & 18th St (NE Corner): BUS330NE');
insert into stops values('BUS230N','Wabash Center on Greenbush St (at Shelter): BUS230N');
insert into stops values('BUS245NW','Market Square (WEST) on Greenbush St: BUS245NW');
insert into stops values('BUS721','Greenbush St & Melbourne Rd (West of): BUS721');
insert into stops values('BUS278NE','Greenbush St & Elmwood Ave (East of): BUS278NE');
insert into stops values('BUS781','Greenbush St & 29th St (West of): BUS781');
insert into stops values('BUS231N','Greenbush St & Sagamore Pkwy N (West of): BUS231N');
insert into stops values('BUS780','Hemlock Rd & Greenbush St (NE Corner): BUS780');
insert into stops values('BUS526NE','Chauncey Ct & Greenbush St (NE Corner): BUS526NE');
insert into stops values('BUS778','Shenandoah Dr & Amherst Dr (SE Corner): BUS778');
insert into stops values('BUS051','Shenandoah Dr at Munger Trail Crossing: BUS051');
insert into stops values('BUS757SE','S Navarre Dr & Shenandoah (SE Corner): BUS757SE');
insert into stops values('BUS341','Shenandoah Dr & Union St (SE Corner): BUS341');
insert into stops values('BUS920SE','Claremont Ln & Shenandoah Dr(SE Corner): BUS920SE');
insert into stops values('BUS759E','S Driftwood & Shenandoah Dr (SE Corner): BUS759E');
insert into stops values('BUS812','Shenandoah Dr & Rome Dr (NE Corner): BUS812');
insert into stops values('BUS760','Executive Dr & Rome Dr (NE Corner): BUS760');
insert into stops values('BUS777','Culvers on Rome Dr (North Side): BUS777');
insert into stops values('BUS879','Creasy Ln & South St (North of, East Side): BUS879');
insert into stops values('BUS762','The Pavilions & Creasy Ln: BUS762');
insert into stops values('BUS461','Sams Club on Creasy Ln: BUS461');
insert into stops values('BUS763E','Fortune Dr & Creasy Ln (SE Corner): BUS763E');
insert into stops values('BUS539','Stinger St & Creasy Ln (SE Corner): BUS539');
insert into stops values('BUS775NE','Harper Dr & Creasy Ln (NE Corner): BUS775NE');
insert into stops values('BUS200N','Harper Dr & Julia Ln (NW Corner): BUS200N');
insert into stops values('BUS765NE','Julia Ln & Sickle Ct (NE Corner) : BUS765NE');
insert into stops values('BUS766E','Sickle Ct & McCarty Ln (NE Corner): BUS766E');
insert into stops values('BUS773','Burberry Place on Creasy Ln (SE Corner): BUS773');
insert into stops values('BUS681','Creasy Ln & Amelia Ave (NE Corner): BUS681');
insert into stops values('BUS770SE','Creasy Ct & Creasy Ln (SE Corner): BUS770SE');
insert into stops values('BUS992','St. Elizabeth Hospital: BUS992');
insert into stops values('BUS923','St Elizabeth Hospital on Creasy (SE Corner):BUS923');
insert into stops values('BUS772','Creasy Ln & SR 38 (Northeast of): BUS772');
insert into stops values('BUS437E','PayLess Supermarket on SR 38: BUS437E');
insert into stops values('BUS157','Roundtable Dr & Shining Armor Ln (SW Corner): BUS157');
insert into stops values('BUS628','Roundtable Dr & Mason Dixon (SE Corner): BUS628');
insert into stops values('BUS110SE','Mason Dixon Dr & Shining Armor Ln (SE):BUS110SE');
insert into stops values('BUS627','Vicksburg Ln & Mason Dixon Dr (SW Corner): BUS627');
insert into stops values('BUS112SE','Morehouse Rd & Mason Dixon Dr (SE Corner):BUS112SE');
insert into stops values('BUS631E','Abnaki Dr & Morehouse Rd: BUS631E');
insert into stops values('BUS113NE','Morehouse Rd & Ellison Dr (East Side): BUS113NE');
insert into stops values('BUS114E','Trailside Flats on Morehouse Rd (East): BUS114E');
insert into stops values('BUS115N','Kalberer Rd & Morehouse Rd (NE Corner): BUS115N');
insert into stops values('BUS944N','West View Apts on Kalberer Rd (North): BUS944N');
insert into stops values('BUS955','Kent Ave @ Purdue Research Center: BUS955');
insert into stops values('BUS956','Win Hentschel Blvd & MED Institute: BUS956');
insert into stops values('BUS957','Mcclure Ave @ Kurz Tech Center: BUS957');
insert into stops values('BUS118','Yeager Rd & Roxboro St (SE Corner): BUS118');
insert into stops values('BUS119','Country Villa Apts on Yeager Rd (SE Corner): BUS119');
insert into stops values('BUS218SE','Yeager Rd & Cumberland Ave (SE Corner): BUS218SE');
insert into stops values('BUS626SE','Montgomery St & Yeager Rd (SE Corner): BUS626SE');
insert into stops values('BUS100E','Beau Jardin Apts on Yeager (SE Corner): BUS100E');
insert into stops values('BUS104N','Anthrop Dr & Yeager Rd (NE Corner): BUS104N');
insert into stops values('BUS101NE','Mayfair Village Apts on Sycamore Ln: BUS101NE');
insert into stops values('BUS624E','Sycamore Ln & Carlisle Rd (SE Corner): BUS624E');
insert into stops values('BUS623SE','Carlisle Rd & Windsor Dr (SE Corner): BUS623SE');
insert into stops values('BUS102NE','Carlisle Rd & Lindberg Rd (North of): BUS102NE');
insert into stops values('BUS375SE','Lindberg Rd & Northwestern Ave (SE Corner): BUS375SE');
insert into stops values('BUS126','Northwestern Ave & Elm Dr (SE Corner): BUS126');
insert into stops values('BUS632','Garden St & Northwestern (SE Corner): BUS632');
insert into stops values('BUS901','Hillcrest Rd & Northwestern (SE Corner): BUS901');
insert into stops values('BUS203','Northwestern Ave & Northridge Dr(SE Corner):BUS203');
insert into stops values('BUS284','Meridian St & Northwestern Ave (SE Corner): BUS284');
insert into stops values('BUS105','Northwestern Ave & Evergreen St(SE Corner): BUS105');
insert into stops values('BUS295','Wang Hall on Northwestern (at Crosswalk): BUS295');
insert into stops values('BUS184','Grissom Hall on Grant St (at Shelter): BUS184');
insert into stops values('BUS260','Krannert Grad School: BUS260');
insert into stops values('BUS248','Columbia St & 4th St (NE Corner): BUS248');
insert into stops values('BUS675','Columbia St & 5th St (NE Corner): BUS675');
insert into stops values('BUS674','Columbia St & 6th St (NE Corner): BUS674');
insert into stops values('BUS243N','Columbia St & 7th St (NE Corner): BUS243N');
insert into stops values('BUS242','Columbia St & 9th St (NE Corner): BUS242');
insert into stops values('BUS309','Columbia St & 12th St (NE Corner): BUS309');
insert into stops values('BUS305','Columbia St & 14th St (NE Corner): BUS305');
insert into stops values('BUS158','Main St & South St (SE Corner): BUS158');
insert into stops values('BUS444NE','Main St & Jackson St (North of): BUS444NE');
insert into stops values('BUS482SE','Main St & Scott St (SE Corner): BUS482SE');
insert into stops values('BUS567','Ford Hall on Stadium Ave: BUS567');
insert into stops values('BUS201','Jischke Dr & Stadium Ave (SE Corner): BUS201');
insert into stops values('BUS362','Wiley Dining/RSC on Jischke Dr: BUS362');
insert into stops values('BUS268E','Redpoint West Lafayette (on Cumberland Ave): BUS268E');
insert into stops values('BUS372','Meijer Ct & Meijer Dr (SW Corner): BUS372');
insert into stops values('BUS277S','SR 26 & Frontage Rd (SW Corner): BUS277S');
insert into stops values('BUS151','Progress Dr & South St (SE Corner): BUS151');
insert into stops values('BUS503','Walmart (East Lafayette): BUS503');
insert into stops values('BUS808','Commerce Dr & Marketplace Dr (SW Corner): BUS808');
insert into stops values('BUS970','Commerce Dr & Park East (SW Corner): BUS970');
insert into stops values('BUS969','Commerce Dr & Fairington Ave (East of): BUS969');
insert into stops values('BUS193E','South St & Creasy Ln (East of): BUS193E');
insert into stops values('BUS384','South St & Executive Dr (SE Corner): BUS384');
insert into stops values('BUS475','South St & 36th St (Southeast of): BUS475');
insert into stops values('BUS405','36th St & South St (NW Corner): BUS405');
insert into stops values('BUS813W','36th St & Coleman Ct (NW Corner @ Bench): BUS813W');
insert into stops values('BUS552SW','Union St & 36th St (SW Corner): BUS552SW');
insert into stops values('BUS971','RRX on Union St (SW Corner): BUS971');
insert into stops values('BUS196E','Earl Ave & Union St (Southeast of): BUS196E');
insert into stops values('BUS507E','Portledge Commons Apts on Earl Ave: BUS507E');
insert into stops values('BUS459SE','Earl Ave & Cason St (SE Corner): BUS459SE');
insert into stops values('BUS128','Ferry St & 31st St (SW Corner): BUS128');
insert into stops values('BUS116S','Ferry St & 28th St (SW Corner): BUS116S');
insert into stops values('BUS244','Ferry St & 26th St (SW Corner): BUS244');
insert into stops values('BUS545S','Ferry St & 23rd St (East of): BUS545S');
insert into stops values('BUS548SW','Ferry St & 21st St (SW Corner): BUS548SW');
insert into stops values('BUS280S','Ferry St & 19th St (SW Corner): BUS280S');
insert into stops values('BUS798SW','Ferry St & Asher St (SW Corner): BUS798SW');
insert into stops values('BUS797S','Ferry St & Perrin Ave (SW Corner): BUS797S');
insert into stops values('BUS796S','Ferry St & Erie St (SW Corner): BUS796S');
insert into stops values('BUS794S','Ferry St & 10th St (South Side): BUS794S');
insert into stops values('BUS532SW','Ferry St & 8th St (SW Corner): BUS532SW');
insert into stops values('BUS534S','Ferry St & 6th St (SW Corner): BUS534S');
insert into stops values('BUS549S','Fowler House Apts on Ferry St (South): BUS549S');
insert into stops values('BUS502','Art Museum on 9th St: BUS502');
insert into stops values('BUS918','Prospect Hill Apts on 18th: BUS918');
insert into stops values('BUS279','9th St & State St (SE Corner): BUS279');
insert into stops values('BUS575','9th St & Kossuth St (South of): BUS575');
insert into stops values('BUS697','9th St & Central Ave (SE Corner): BUS697');
insert into stops values('BUS528','9th St & King St (SE Corner): BUS527');
insert into stops values('BUS241','Logan Ave & 9th St (NE Corner): BUS241');
insert into stops values('BUS544NE','Logan Ave & 14th St (NE Corner): BUS544NE');
insert into stops values('BUS327NE','Logan Ave & El Prado Ave (NE Corner): BUS327NE');
insert into stops values('BUS986N','Logan Ave & 18th St (West of): BUS986N');
insert into stops values('BUS198','18th St & JR Hiatt Dr (NE Corner): BUS198');
insert into stops values('BUS738','18th St & Iroquois Tr (SE Corner): BUS738');
insert into stops values('BUS776','Beck Ln & 18th St (West of): BUS776');
insert into stops values('BUS682S','Edgelea School on Beck Ln (West Drive): BUS682S');
insert into stops values('BUS553','Circle Pines on David Ross Rd (NW Corner): BUS553');
insert into stops values('BUS554E','Alpha Chi on David Ross Rd (East): BUS554E');
insert into stops values('BUS562N','Theta Chi on Tower Dr (North): BUS562N');
insert into stops values('BUS472N','Hilltop Dr & Tower Dr (NE Corner): BUS472N');
insert into stops values('BUS509NE','Jischke Dr & Tower Dr (NE Corner): BUS509NE');
insert into stops values('BUS213','Steven Beering Dr & Tower Dr (Southeast of): BUS213');
insert into stops values('BUS800','Russell St & 6th St (SE Corner): BUS800');
insert into stops values('BUS810','Russell St & 4th St (SE Corner): BUS810');
insert into stops values('BUS805','Russell St & 2nd St (NE Corner): BUS805');
insert into stops values('BUS169','Northwestern Ave & Chelsea Rd (West Side): BUS169');
insert into stops values('BUS431','Cherry Ln & Northwestern Ave (South of): BUS431');
insert into stops values('BUS476','Northwestern Ave & Carrolton Blvd (NW Corner): BUS476');
insert into stops values('BUS629','Garden St & Northwestern (NW Corner): BUS629');
insert into stops values('BUS375SW','Northwestern Ave & Lindberg Rd (Southwest of): BUS375SW');
insert into stops values('BUS952','Lindberg & Northwestern (North East of): BUS952');
insert into stops values('BUS102NW','Carlisle Rd & Lindberg Rd (NW Corner): BUS102NW');
insert into stops values('BUS623NW','Carlisle Rd & Windsor Dr (NW Corner): BUS623NW');
insert into stops values('BUS624W','Sycamore Ln & Carlisle Rd (West of): BUS624W');
insert into stops values('BUS101SW','Mayfair Village Apts on Sycamore Ln: BUS101SW');
insert into stops values('BUS104S','Yeager Rd & Anthrop Dr (at Shelter): BUS104S');
insert into stops values('BUS100W','Beau Jardin Apts on Yeager (at Shelter): BUS100W');
insert into stops values('BUS626NW','Montgomery St & Yeager Rd (NW Corner): BUS626NW');
insert into stops values('BUS218NW','Yeager Rd & Cumberland Ave (NW Corner): BUS218NW');
insert into stops values('BUS129','Peppermill Apts on Yeager Rd (NW Corner): BUS129');
insert into stops values('BUS117','Yeager Rd & McClure Ave (SW Corner): BUS117');
insert into stops values('BUS048','Mcclure Ave @ Kurz Tech Center: BUS048');
insert into stops values('BUS047','Win Hentschel Blvd & MED Institute: BUS047');
insert into stops values('BUS046','Kent Ave @ Purdue Research Center: BUS046');
insert into stops values('BUS945SW','Kent Ave & Kalberer Rd (SW Corner): BUS945SW');
insert into stops values('BUS944S','West View Apts on Kalberer Rd (South): BUS944S');
insert into stops values('BUS115S','Kalberer Rd & Morehouse Rd (SE Corner): BUS115S');
insert into stops values('BUS114W','Trailside Flats on Morehouse Rd (West): BUS114W');
insert into stops values('BUS113NW','Morehouse Rd & Ellison Dr (West Side): BUS113NW');
insert into stops values('BUS631W','Abnaki Dr & Morehouse Rd: BUS631W');
insert into stops values('BUS112NE','Mason Dixon Dr & Morehouse Rd (NE Corner):BUS112NE');
insert into stops values('BUS630','Military Ct & Mason Dixon Dr (NE Corner): BUS630');
insert into stops values('BUS110NE','Shining Armor Ln & Mason Dixon Dr (NE): BUS110NE');
insert into stops values('BUS941SE','Creasy Ln & Bonlou (SE Corner): BUS941SE');
insert into stops values('BUS142S','Ivy Tech on Creasy Ln (at Shelter): BUS142S');
insert into stops values('BUS966','Griffin Hall on Creasy Ln: BUS966');
insert into stops values('BUS711S','Brady Ln & Imperial Pkwy (SW Corner): BUS711S');
insert into stops values('BUS712','Brady Ln & Reagan Dr (SW Corner): BUS712');
insert into stops values('BUS710S','Village Pantry on Brady Ln (South Side): BUS710S');
insert into stops values('BUS301S','Pheasant Run Apts on Brady Ln (South): BUS301S');
insert into stops values('BUS708','Brady Ln & Winter St (SW Corner): BUS708');
insert into stops values('BUS181','RRX on Brady Ln (SW Corner): BUS181');
insert into stops values('BUS449S','Brady Ln & Commanche Trl (SE Corner): BUS449S');
insert into stops values('BUS707S','Brady Ln & Pipers Glen Dr (SW Corner): BUS707S');
insert into stops values('BUS354','Brady Ln & 18th St (East of): BUS354');
insert into stops values('BUS865','18th St & Eastway St (NW Corner): BUS865');
insert into stops values('BUS807','Manitou Dr & 18th St (NW Corner): BUS807');
insert into stops values('BUS155','Edgelea Elementary School on 18th St: BUS155');
insert into stops values('BUS344','Beck Ln and Cayuga Tr (NE Corner): BUS344');
insert into stops values('BUS416','Summerfield Dr & Beck Ln (NW Corner): BUS416');
insert into stops values('BUS730','Summerfield Dr & Hiawatha Ln (NW Corner): BUS730');
insert into stops values('BUS428S','Iroquois Tr & Summerfield Dr (SW Corner): BUS428S');
insert into stops values('BUS729','Osage Dr & Iroquois Tr (NW Corner): BUS729');
insert into stops values('BUS409','Shoshone Dr & Osage Dr (SW Corner): BUS409');
insert into stops values('BUS469S','Georgetown Apts on Shoshone Dr (South): BUS469S');
insert into stops values('BUS963','18th St & Meadow Dr (South of): BUS963');
insert into stops values('BUS331','Teal Rd & 22nd St (East Of): BUS331');
insert into stops values('BUS311','Rural King on 26th St (at Shelter): BUS311');
insert into stops values('BUS414','26th St & Gregory Ave (NW Corner): BUS414');
insert into stops values('BUS378SW','State St & Earl Ave (SW Corner): BUS378SW');
insert into stops values('BUS727','State St & 22nd St (SW Corner): BUS727');
insert into stops values('BUS726S','State St & 20th St (SW Corner): BUS726S');
insert into stops values('BUS256S','State St & 18th St (SE Corner): BUS256S');
insert into stops values('BUS725W','18th St & Adams St (NW Corner): BUS725W');
insert into stops values('BUS724','18th St & Congress St (NW Corner): BUS724');
insert into stops values('BUS940','18th St & Larue St (South of): BUS940');
insert into stops values('BUS723','18th St & Center St (North of): BUS723');
insert into stops values('BUS740','18th St & Everett St (SE Corner): BUS740');
insert into stops values('BUS662','18th St & Congress St (NE Corner): BUS662');
insert into stops values('BUS725E','18th St & Adams St (SE Corner): BUS725E');
insert into stops values('BUS256N','State St & 18th St (NE Corner): BUS256N');
insert into stops values('BUS726N','State St & 20th St (NE Corner): BUS726N');
insert into stops values('BUS378NW','State St & Earl Ave (West of): BUS378NW');
insert into stops values('BUS467','22nd St & Teal Rd (North of): BUS467');
insert into stops values('BUS420','18th St & Teal Rd (SE Corner): BUS420');
insert into stops values('BUS739','18th St & Shoshone Dr (NE Corner): BUS739');
insert into stops values('BUS469N','Georgetown Apts on Shoshone Dr (North): BUS469N');
insert into stops values('BUS315N','Shoshone Dr & Osage Dr (West of): BUS315N');
insert into stops values('BUS428N','Iroquois Tr & Summerfield Dr (Northwest of): BUS428N');
insert into stops values('BUS942','Summerfield Dr & Ottawa Dr (SE Corner): BUS942');
insert into stops values('BUS737','Summerfield Dr & Maumee Pl (SE Corner): BUS737');
insert into stops values('BUS731E','Commanche Tr & Beck Ln (SE Corner): BUS731E');
insert into stops values('BUS736','Commanche Tr & Yuma Ave (SE Corner): BUS736');
insert into stops values('BUS408','Main St & 21st St (Northeast of): BUS408');
insert into stops values('BUS191','Frozen Custard on Main St: BUS191');
insert into stops values('BUS216E','Main St & 24th St (North of): BUS216E');
insert into stops values('BUS663NE','Main St & S 25th St (NE Corner): BUS663NE');
insert into stops values('BUS664NW','Main St & S 28th St (NW Corner): BUS664NW');
insert into stops values('BUS531NE','Main St & Earl Ave (Northeast of) : BUS531NE');
insert into stops values('BUS506','Main St & McCarty Ln (Southeast of): BUS506');
insert into stops values('BUS678','Main St & Sagamore Pkwy S (NW Corner): BUS678');
insert into stops values('BUS946','SR 38 @ Golden Lion: BUS946');
insert into stops values('BUS462','SR 38 at Lafayette Marketplace: BUS462');
insert into stops values('BUS677','SR 38 & Kingsway Dr (Northeast of): BUS677');
insert into stops values('BUS671','Wendys at Tippecanoe Mall (North Side): BUS671');
insert into stops values('BUS676','Sears at Tippecanoe Mall: BUS676');
insert into stops values('BUS373','Tippecanoe Mall Entrance E: BUS373');
insert into stops values('BUS982','IU Arnett Hospital: BUS982');
insert into stops values('BUS625','Park East Blvd & Retail Dr (SW Corner): BUS625');
insert into stops values('BUS615','Mezzanine Dr & Park East Blvd (SW Corner): BUS615');
insert into stops values('BUS601','Arnett Clinic on Mezzanine Dr: BUS601');
insert into stops values('BUS997','Mezzanine Dr & McCarty Ln (Northwest of): BUS997');
insert into stops values('BUS996','McCarty Ln & Burberry Dr (SW Corner): BUS996');
insert into stops values('BUS895','McCarty Ln & Emerald Pine Ct: BUS895');
insert into stops values('BUS995','McCarty Ln & Landmark Dr (South of): BUS995');
insert into stops values('BUS994','McCarty Ln & Kepner Dr (SW Corner): BUS994');
insert into stops values('BUS120','McCarty Ln & Industrial Dr (SW Corner): BUS120');
insert into stops values('BUS298','McCarty Ln & Sagamore Pkwy S (East of): BUS298');
insert into stops values('BUS967','South St & Thompson St (SW Corner): BUS967');
insert into stops values('BUS962','South St & Douglas St (SW Corner): BUS962');
insert into stops values('BUS206','South St & 14th St (SW Corner): BUS206');
insert into stops values('BUS661','South St & McGrath Ave (West of): BUS661');
insert into stops values('BUS659','South St & 10th St (West of): BUS659');
insert into stops values('BUS351','Tippecanoe Co Public Library on South St: BUS351');
insert into stops values('BUS329','South St & 5th St (SW Corner): BUS329');
insert into stops values('BUS265','South St & 4th St (SW Corner): BUS265');
insert into stops values('BUS215','CityBus Center: BUS215');
insert into stops values('BUS968','McCarty Ln & Mezzannine');
insert into stops values('BUS287','2nd St & Columbia St (NW Corner): BUS287');
insert into stops values('BUS188','2nd St & Main St (SE Corner): BUS188');
insert into stops values('BUS166','State Street Office Facility: BUS166');
insert into stops values('BUS326','S Chauncey Ave & Wood St (SE Corner): BUS326');
insert into stops values('TEMP06','Northwestern Ave & Cherry Lane (NW Corner): TEMP06');
insert into stops values('TEMP584SW','1st St & Jischke Dr (SW Corner): TEMP584SW');
insert into stops values('BUS701','Poland Hill Rd and Beck Ln (South of)');
insert into stops values('BUS214','Old Romney Rd & US52 / SR25 (NE Corner): BUS214');
insert into stops values('BUS312','The Quarters Clubhouse: BUS312');
insert into stops values('BUS419','State St & Newman Rd (SE Corner): BUS419');
insert into stops values('TEMP04','Russell & 6th');
insert into stops values('BUS160','Tick Tock Tavern: BUS160');
insert into stops values('BUS002','3rd St & Ferry St (NW Corner): BUS002');
insert into stops values('BUS694SW','South St & 26th St (SW Corner)');
insert into stops values('BUS221W','178 Sagamore Pkwy S: BUS221W');
insert into stops values('BUS219W','Sagamore Pkwy S & National Dr (NW Corner): BUS219W');
insert into stops values('BUS219E','Sagamore Pkwy S & National Dr (SE Corner): BUS219E');
insert into stops values('BUS221E','181 Sagamore Pkwy S: BUS221E');
insert into stops values('BUS695SW','South St & 29th St (SW Corner)');
insert into stops values('BUS696SW','South St & Earl Ave (SW Corner)');
insert into stops values('BUS699SW','South St & Sagamore Pkwy S (SW Corner)');
insert into stops values('BUS696NE','South St @ RRX');
insert into stops values('BUS695NE','South St & 29th St (NE Corner)');
insert into stops values('BUS694NE','South St & 26th St (NE Corner)');
insert into stops values('BUS185','2nd St & Columbia St (SE Corner): BUS185');
insert into stops values('BUSLSS','Lafayette SunnySide School');
insert into stops values('BUS668','Kirby Riskk Manufacturing Center');
insert into stops values('BUS648','Alabama St & 3rd Street (West of)');
insert into stops values('BUS389','Beering Hall on University St: BUS389');
insert into stops values('BUS387','University St & 2nd St (NW Corner): BUS387');
insert into stops values('BUS563','PUSH at University St & 5th St');
insert into stops values('BUS569','PUSH at University St & 5th St');
insert into stops values('TEMP899','Morgan & Jischke Dr (SE Corner)');

insert into stops values('TEMP','Tilbury Dr & US 231 S');
insert into stops values('BUS171','Meijer West Lafayette: BUS171');

insert into stops values('BUS168','Entomology Field Operations Building: BUS168');
insert into stops values('BUS167','State St & US-231 (East of): BUS167');
insert into stops values('BUS011','Aspire Apts at Discovery Park: BUS011');
insert into stops values('BUS540','Pi Beta Phi on Russell St');
