

create table schedules (
	schedule_id int auto_increment primary key, 
	route_id int,
	dayOftheWeek int,  
	start_time time,
    end_time time,
    direction int,
	foreign key (route_id) references route(route_id)
    ); 




insert into schedules values(NULL,10238,1,'09:00','10:00',1);
insert into schedules values(NULL,10239,1,'09:00','10:00',1);
insert into schedules values(NULL,10241,1,'09:00','10:00',1);
insert into schedules values(NULL,10242,1,'09:00','10:00',1);
insert into schedules values(NULL,10244,1,'09:00','10:00',1);

insert into schedules values(NULL,10247,1,'09:00','10:00',1);
insert into schedules values(NULL,10249,1,'09:00','10:00',1);
insert into schedules values(NULL,10251,1,'09:00','10:00',1);











insert into schedules values(NULL,10238,1,'10:00','11:00',1);
insert into schedules values(NULL,10239,1,'10:00','11:00',1);
insert into schedules values(NULL,10241,1,'10:00','11:00',1);
insert into schedules values(NULL,10242,1,'10:00','11:00',1);
insert into schedules values(NULL,10244,1,'10:00','11:00',1);

insert into schedules values(NULL,10247,1,'10:00','11:00',1);
insert into schedules values(NULL,10249,1,'10:00','11:00',1);
insert into schedules values(NULL,10251,1,'10:00','11:00',1);











insert into schedules values(NULL,10238,1,'11:00','12:00',1);
insert into schedules values(NULL,10239,1,'11:00','12:00',1);
insert into schedules values(NULL,10241,1,'11:00','12:00',1);
insert into schedules values(NULL,10242,1,'11:00','12:00',1);
insert into schedules values(NULL,10244,1,'11:00','12:00',1);
insert into schedules values(NULL,10245,1,'11:00','12:00',1);
insert into schedules values(NULL,10247,1,'11:00','12:00',1);
insert into schedules values(NULL,10249,1,'11:00','12:00',1);
insert into schedules values(NULL,10251,1,'11:00','12:00',1);











insert into schedules values(NULL,10238,1,'12:00','13:00',1);
insert into schedules values(NULL,10239,1,'12:00','13:00',1);
insert into schedules values(NULL,10241,1,'12:00','13:00',1);
insert into schedules values(NULL,10242,1,'12:00','13:00',1);
insert into schedules values(NULL,10244,1,'12:00','13:00',1);
insert into schedules values(NULL,10245,1,'12:00','13:00',1);
insert into schedules values(NULL,10247,1,'12:00','13:00',1);
insert into schedules values(NULL,10249,1,'12:00','13:00',1);
insert into schedules values(NULL,10251,1,'12:00','13:00',1);











insert into schedules values(NULL,10238,1,'13:00','14:00',1);
insert into schedules values(NULL,10239,1,'13:00','14:00',1);
insert into schedules values(NULL,10241,1,'13:00','14:00',1);
insert into schedules values(NULL,10242,1,'13:00','14:00',1);
insert into schedules values(NULL,10244,1,'13:00','14:00',1);
insert into schedules values(NULL,10245,1,'13:00','14:00',1);
insert into schedules values(NULL,10247,1,'13:00','14:00',1);
insert into schedules values(NULL,10249,1,'13:00','14:00',1);
insert into schedules values(NULL,10251,1,'13:00','14:00',1);











insert into schedules values(NULL,10238,1,'14:00','15:00',1);
insert into schedules values(NULL,10239,1,'14:00','15:00',1);
insert into schedules values(NULL,10241,1,'14:00','15:00',1);
insert into schedules values(NULL,10242,1,'14:00','15:00',1);
insert into schedules values(NULL,10244,1,'14:00','15:00',1);
insert into schedules values(NULL,10245,1,'14:00','15:00',1);
insert into schedules values(NULL,10247,1,'14:00','15:00',1);
insert into schedules values(NULL,10249,1,'14:00','15:00',1);
insert into schedules values(NULL,10251,1,'14:00','15:00',1);











insert into schedules values(NULL,10238,1,'15:00','16:00',1);
insert into schedules values(NULL,10239,1,'15:00','16:00',1);
insert into schedules values(NULL,10241,1,'15:00','16:00',1);
insert into schedules values(NULL,10242,1,'15:00','16:00',1);
insert into schedules values(NULL,10244,1,'15:00','16:00',1);
insert into schedules values(NULL,10245,1,'15:00','16:00',1);
insert into schedules values(NULL,10247,1,'15:00','16:00',1);
insert into schedules values(NULL,10249,1,'15:00','16:00',1);
insert into schedules values(NULL,10251,1,'15:00','16:00',1);











insert into schedules values(NULL,10238,1,'16:00','17:00',1);
insert into schedules values(NULL,10239,1,'16:00','17:00',1);
insert into schedules values(NULL,10241,1,'16:00','17:00',1);
insert into schedules values(NULL,10242,1,'16:00','17:00',1);
insert into schedules values(NULL,10244,1,'16:00','17:00',1);
insert into schedules values(NULL,10245,1,'16:00','17:00',1);
insert into schedules values(NULL,10247,1,'16:00','17:00',1);
insert into schedules values(NULL,10249,1,'16:00','17:00',1);
insert into schedules values(NULL,10251,1,'16:00','17:00',1);











insert into schedules values(NULL,10238,1,'17:00','18:00',1);
insert into schedules values(NULL,10239,1,'17:00','18:00',1);
insert into schedules values(NULL,10241,1,'17:00','18:00',1);
insert into schedules values(NULL,10242,1,'17:00','18:00',1);
insert into schedules values(NULL,10244,1,'17:00','18:00',1);
insert into schedules values(NULL,10245,1,'17:00','18:00',1);
insert into schedules values(NULL,10247,1,'17:00','18:00',1);
insert into schedules values(NULL,10249,1,'17:00','18:00',1);
insert into schedules values(NULL,10251,1,'17:00','18:00',1);











insert into schedules values(NULL,10238,1,'18:00','19:00',1);
insert into schedules values(NULL,10239,1,'18:00','19:00',1);
insert into schedules values(NULL,10241,1,'18:00','19:00',1);
insert into schedules values(NULL,10242,1,'18:00','19:00',1);
insert into schedules values(NULL,10244,1,'18:00','19:00',1);
insert into schedules values(NULL,10245,1,'18:00','19:00',1);
insert into schedules values(NULL,10247,1,'18:00','19:00',1);
insert into schedules values(NULL,10249,1,'18:00','19:00',1);
insert into schedules values(NULL,10251,1,'18:00','19:00',1);











insert into schedules values(NULL,10238,1,'19:00','20:00',1);
insert into schedules values(NULL,10239,1,'19:00','20:00',1);
insert into schedules values(NULL,10241,1,'19:00','20:00',1);
insert into schedules values(NULL,10242,1,'19:00','20:00',1);
insert into schedules values(NULL,10244,1,'19:00','20:00',1);
insert into schedules values(NULL,10245,1,'19:00','20:00',1);
insert into schedules values(NULL,10247,1,'19:00','20:00',1);
insert into schedules values(NULL,10249,1,'19:00','20:00',1);
insert into schedules values(NULL,10251,1,'19:00','20:00',1);











insert into schedules values(NULL,10238,2,'09:00','10:00',0);
insert into schedules values(NULL,10239,2,'09:00','10:00',0);
insert into schedules values(NULL,10241,2,'09:00','10:00',0);
insert into schedules values(NULL,10242,2,'09:00','10:00',0);
insert into schedules values(NULL,10244,2,'09:00','10:00',0);
insert into schedules values(NULL,10245,2,'09:00','10:00',0);
insert into schedules values(NULL,10247,2,'09:00','10:00',0);
insert into schedules values(NULL,10249,2,'09:00','10:00',0);
insert into schedules values(NULL,10251,2,'09:00','10:00',0);











insert into schedules values(NULL,10238,2,'10:00','11:00',0);
insert into schedules values(NULL,10239,2,'10:00','11:00',0);
insert into schedules values(NULL,10241,2,'10:00','11:00',0);
insert into schedules values(NULL,10242,2,'10:00','11:00',0);
insert into schedules values(NULL,10244,2,'10:00','11:00',0);
insert into schedules values(NULL,10245,2,'10:00','11:00',0);
insert into schedules values(NULL,10247,2,'10:00','11:00',0);
insert into schedules values(NULL,10249,2,'10:00','11:00',0);
insert into schedules values(NULL,10251,2,'10:00','11:00',0);











insert into schedules values(NULL,10238,2,'11:00','12:00',0);
insert into schedules values(NULL,10239,2,'11:00','12:00',0);
insert into schedules values(NULL,10241,2,'11:00','12:00',0);
insert into schedules values(NULL,10242,2,'11:00','12:00',0);
insert into schedules values(NULL,10244,2,'11:00','12:00',0);
insert into schedules values(NULL,10245,2,'11:00','12:00',0);
insert into schedules values(NULL,10247,2,'11:00','12:00',0);
insert into schedules values(NULL,10249,2,'11:00','12:00',0);
insert into schedules values(NULL,10251,2,'11:00','12:00',0);











insert into schedules values(NULL,10238,2,'12:00','13:00',0);
insert into schedules values(NULL,10239,2,'12:00','13:00',0);
insert into schedules values(NULL,10241,2,'12:00','13:00',0);
insert into schedules values(NULL,10242,2,'12:00','13:00',0);
insert into schedules values(NULL,10244,2,'12:00','13:00',0);
insert into schedules values(NULL,10245,2,'12:00','13:00',0);
insert into schedules values(NULL,10247,2,'12:00','13:00',0);
insert into schedules values(NULL,10249,2,'12:00','13:00',0);
insert into schedules values(NULL,10251,2,'12:00','13:00',0);











insert into schedules values(NULL,10238,2,'13:00','14:00',0);
insert into schedules values(NULL,10239,2,'13:00','14:00',0);
insert into schedules values(NULL,10241,2,'13:00','14:00',0);
insert into schedules values(NULL,10242,2,'13:00','14:00',0);
insert into schedules values(NULL,10244,2,'13:00','14:00',0);
insert into schedules values(NULL,10245,2,'13:00','14:00',0);
insert into schedules values(NULL,10247,2,'13:00','14:00',0);
insert into schedules values(NULL,10249,2,'13:00','14:00',0);
insert into schedules values(NULL,10251,2,'13:00','14:00',0);











insert into schedules values(NULL,10238,2,'14:00','15:00',0);
insert into schedules values(NULL,10239,2,'14:00','15:00',0);
insert into schedules values(NULL,10241,2,'14:00','15:00',0);
insert into schedules values(NULL,10242,2,'14:00','15:00',0);
insert into schedules values(NULL,10244,2,'14:00','15:00',0);
insert into schedules values(NULL,10245,2,'14:00','15:00',0);
insert into schedules values(NULL,10247,2,'14:00','15:00',0);
insert into schedules values(NULL,10249,2,'14:00','15:00',0);
insert into schedules values(NULL,10251,2,'14:00','15:00',0);











insert into schedules values(NULL,10238,2,'15:00','16:00',0);
insert into schedules values(NULL,10239,2,'15:00','16:00',0);
insert into schedules values(NULL,10241,2,'15:00','16:00',0);
insert into schedules values(NULL,10242,2,'15:00','16:00',0);
insert into schedules values(NULL,10244,2,'15:00','16:00',0);
insert into schedules values(NULL,10245,2,'15:00','16:00',0);
insert into schedules values(NULL,10247,2,'15:00','16:00',0);
insert into schedules values(NULL,10249,2,'15:00','16:00',0);
insert into schedules values(NULL,10251,2,'15:00','16:00',0);











insert into schedules values(NULL,10238,2,'16:00','17:00',0);
insert into schedules values(NULL,10239,2,'16:00','17:00',0);
insert into schedules values(NULL,10241,2,'16:00','17:00',0);
insert into schedules values(NULL,10242,2,'16:00','17:00',0);
insert into schedules values(NULL,10244,2,'16:00','17:00',0);
insert into schedules values(NULL,10245,2,'16:00','17:00',0);
insert into schedules values(NULL,10247,2,'16:00','17:00',0);
insert into schedules values(NULL,10249,2,'16:00','17:00',0);
insert into schedules values(NULL,10251,2,'16:00','17:00',0);











insert into schedules values(NULL,10238,2,'17:00','18:00',0);
insert into schedules values(NULL,10239,2,'17:00','18:00',0);
insert into schedules values(NULL,10241,2,'17:00','18:00',0);
insert into schedules values(NULL,10242,2,'17:00','18:00',0);
insert into schedules values(NULL,10244,2,'17:00','18:00',0);
insert into schedules values(NULL,10245,2,'17:00','18:00',0);
insert into schedules values(NULL,10247,2,'17:00','18:00',0);
insert into schedules values(NULL,10249,2,'17:00','18:00',0);
insert into schedules values(NULL,10251,2,'17:00','18:00',0);











insert into schedules values(NULL,10238,2,'18:00','19:00',0);
insert into schedules values(NULL,10239,2,'18:00','19:00',0);
insert into schedules values(NULL,10241,2,'18:00','19:00',0);
insert into schedules values(NULL,10242,2,'18:00','19:00',0);
insert into schedules values(NULL,10244,2,'18:00','19:00',0);
insert into schedules values(NULL,10245,2,'18:00','19:00',0);
insert into schedules values(NULL,10247,2,'18:00','19:00',0);
insert into schedules values(NULL,10249,2,'18:00','19:00',0);
insert into schedules values(NULL,10251,2,'18:00','19:00',0);











insert into schedules values(NULL,10238,2,'19:00','20:00',0);
insert into schedules values(NULL,10239,2,'19:00','20:00',0);
insert into schedules values(NULL,10241,2,'19:00','20:00',0);
insert into schedules values(NULL,10242,2,'19:00','20:00',0);
insert into schedules values(NULL,10244,2,'19:00','20:00',0);
insert into schedules values(NULL,10245,2,'19:00','20:00',0);
insert into schedules values(NULL,10247,2,'19:00','20:00',0);
insert into schedules values(NULL,10249,2,'19:00','20:00',0);
insert into schedules values(NULL,10251,2,'19:00','20:00',0);











insert into schedules values(NULL,10238,2,'09:00','10:00',1);
insert into schedules values(NULL,10239,2,'09:00','10:00',1);
insert into schedules values(NULL,10241,2,'09:00','10:00',1);
insert into schedules values(NULL,10242,2,'09:00','10:00',1);
insert into schedules values(NULL,10244,2,'09:00','10:00',1);
insert into schedules values(NULL,10245,2,'09:00','10:00',1);
insert into schedules values(NULL,10247,2,'09:00','10:00',1);
insert into schedules values(NULL,10249,2,'09:00','10:00',1);
insert into schedules values(NULL,10251,2,'09:00','10:00',1);











insert into schedules values(NULL,10238,2,'10:00','11:00',1);
insert into schedules values(NULL,10239,2,'10:00','11:00',1);
insert into schedules values(NULL,10241,2,'10:00','11:00',1);
insert into schedules values(NULL,10242,2,'10:00','11:00',1);
insert into schedules values(NULL,10244,2,'10:00','11:00',1);
insert into schedules values(NULL,10245,2,'10:00','11:00',1);
insert into schedules values(NULL,10247,2,'10:00','11:00',1);
insert into schedules values(NULL,10249,2,'10:00','11:00',1);
insert into schedules values(NULL,10251,2,'10:00','11:00',1);











insert into schedules values(NULL,10238,2,'11:00','12:00',1);
insert into schedules values(NULL,10239,2,'11:00','12:00',1);
insert into schedules values(NULL,10241,2,'11:00','12:00',1);
insert into schedules values(NULL,10242,2,'11:00','12:00',1);
insert into schedules values(NULL,10244,2,'11:00','12:00',1);
insert into schedules values(NULL,10245,2,'11:00','12:00',1);
insert into schedules values(NULL,10247,2,'11:00','12:00',1);
insert into schedules values(NULL,10249,2,'11:00','12:00',1);
insert into schedules values(NULL,10251,2,'11:00','12:00',1);











insert into schedules values(NULL,10238,2,'12:00','13:00',1);
insert into schedules values(NULL,10239,2,'12:00','13:00',1);
insert into schedules values(NULL,10241,2,'12:00','13:00',1);
insert into schedules values(NULL,10242,2,'12:00','13:00',1);
insert into schedules values(NULL,10244,2,'12:00','13:00',1);
insert into schedules values(NULL,10245,2,'12:00','13:00',1);
insert into schedules values(NULL,10247,2,'12:00','13:00',1);
insert into schedules values(NULL,10249,2,'12:00','13:00',1);
insert into schedules values(NULL,10251,2,'12:00','13:00',1);











insert into schedules values(NULL,10238,2,'13:00','14:00',1);
insert into schedules values(NULL,10239,2,'13:00','14:00',1);
insert into schedules values(NULL,10241,2,'13:00','14:00',1);
insert into schedules values(NULL,10242,2,'13:00','14:00',1);
insert into schedules values(NULL,10244,2,'13:00','14:00',1);
insert into schedules values(NULL,10245,2,'13:00','14:00',1);
insert into schedules values(NULL,10247,2,'13:00','14:00',1);
insert into schedules values(NULL,10249,2,'13:00','14:00',1);
insert into schedules values(NULL,10251,2,'13:00','14:00',1);











insert into schedules values(NULL,10238,2,'14:00','15:00',1);
insert into schedules values(NULL,10239,2,'14:00','15:00',1);
insert into schedules values(NULL,10241,2,'14:00','15:00',1);
insert into schedules values(NULL,10242,2,'14:00','15:00',1);
insert into schedules values(NULL,10244,2,'14:00','15:00',1);
insert into schedules values(NULL,10245,2,'14:00','15:00',1);
insert into schedules values(NULL,10247,2,'14:00','15:00',1);
insert into schedules values(NULL,10249,2,'14:00','15:00',1);
insert into schedules values(NULL,10251,2,'14:00','15:00',1);











insert into schedules values(NULL,10238,2,'15:00','16:00',1);
insert into schedules values(NULL,10239,2,'15:00','16:00',1);
insert into schedules values(NULL,10241,2,'15:00','16:00',1);
insert into schedules values(NULL,10242,2,'15:00','16:00',1);
insert into schedules values(NULL,10244,2,'15:00','16:00',1);
insert into schedules values(NULL,10245,2,'15:00','16:00',1);
insert into schedules values(NULL,10247,2,'15:00','16:00',1);
insert into schedules values(NULL,10249,2,'15:00','16:00',1);
insert into schedules values(NULL,10251,2,'15:00','16:00',1);











insert into schedules values(NULL,10238,2,'16:00','17:00',1);
insert into schedules values(NULL,10239,2,'16:00','17:00',1);
insert into schedules values(NULL,10241,2,'16:00','17:00',1);
insert into schedules values(NULL,10242,2,'16:00','17:00',1);
insert into schedules values(NULL,10244,2,'16:00','17:00',1);
insert into schedules values(NULL,10245,2,'16:00','17:00',1);
insert into schedules values(NULL,10247,2,'16:00','17:00',1);
insert into schedules values(NULL,10249,2,'16:00','17:00',1);
insert into schedules values(NULL,10251,2,'16:00','17:00',1);











insert into schedules values(NULL,10238,2,'17:00','18:00',1);
insert into schedules values(NULL,10239,2,'17:00','18:00',1);
insert into schedules values(NULL,10241,2,'17:00','18:00',1);
insert into schedules values(NULL,10242,2,'17:00','18:00',1);
insert into schedules values(NULL,10244,2,'17:00','18:00',1);
insert into schedules values(NULL,10245,2,'17:00','18:00',1);
insert into schedules values(NULL,10247,2,'17:00','18:00',1);
insert into schedules values(NULL,10249,2,'17:00','18:00',1);
insert into schedules values(NULL,10251,2,'17:00','18:00',1);











insert into schedules values(NULL,10238,2,'18:00','19:00',1);
insert into schedules values(NULL,10239,2,'18:00','19:00',1);
insert into schedules values(NULL,10241,2,'18:00','19:00',1);
insert into schedules values(NULL,10242,2,'18:00','19:00',1);
insert into schedules values(NULL,10244,2,'18:00','19:00',1);
insert into schedules values(NULL,10245,2,'18:00','19:00',1);
insert into schedules values(NULL,10247,2,'18:00','19:00',1);
insert into schedules values(NULL,10249,2,'18:00','19:00',1);
insert into schedules values(NULL,10251,2,'18:00','19:00',1);











insert into schedules values(NULL,10238,2,'19:00','20:00',1);
insert into schedules values(NULL,10239,2,'19:00','20:00',1);
insert into schedules values(NULL,10241,2,'19:00','20:00',1);
insert into schedules values(NULL,10242,2,'19:00','20:00',1);
insert into schedules values(NULL,10244,2,'19:00','20:00',1);
insert into schedules values(NULL,10245,2,'19:00','20:00',1);
insert into schedules values(NULL,10247,2,'19:00','20:00',1);
insert into schedules values(NULL,10249,2,'19:00','20:00',1);
insert into schedules values(NULL,10251,2,'19:00','20:00',1);











insert into schedules values(NULL,10239,3,'09:00','10:00',0);
insert into schedules values(NULL,10241,3,'09:00','10:00',0);
insert into schedules values(NULL,10242,3,'09:00','10:00',0);
insert into schedules values(NULL,10244,3,'09:00','10:00',0);
insert into schedules values(NULL,10245,3,'09:00','10:00',0);
insert into schedules values(NULL,10247,3,'09:00','10:00',0);
insert into schedules values(NULL,10249,3,'09:00','10:00',0);
insert into schedules values(NULL,10251,3,'09:00','10:00',0);











insert into schedules values(NULL,10238,3,'10:00','11:00',0);
insert into schedules values(NULL,10239,3,'10:00','11:00',0);
insert into schedules values(NULL,10241,3,'10:00','11:00',0);
insert into schedules values(NULL,10242,3,'10:00','11:00',0);
insert into schedules values(NULL,10244,3,'10:00','11:00',0);
insert into schedules values(NULL,10245,3,'10:00','11:00',0);
insert into schedules values(NULL,10247,3,'10:00','11:00',0);
insert into schedules values(NULL,10249,3,'10:00','11:00',0);
insert into schedules values(NULL,10251,3,'10:00','11:00',0);











insert into schedules values(NULL,10238,3,'11:00','12:00',0);
insert into schedules values(NULL,10239,3,'11:00','12:00',0);
insert into schedules values(NULL,10241,3,'11:00','12:00',0);
insert into schedules values(NULL,10242,3,'11:00','12:00',0);
insert into schedules values(NULL,10244,3,'11:00','12:00',0);
insert into schedules values(NULL,10245,3,'11:00','12:00',0);
insert into schedules values(NULL,10247,3,'11:00','12:00',0);
insert into schedules values(NULL,10249,3,'11:00','12:00',0);
insert into schedules values(NULL,10251,3,'11:00','12:00',0);











insert into schedules values(NULL,10238,3,'12:00','13:00',0);
insert into schedules values(NULL,10239,3,'12:00','13:00',0);
insert into schedules values(NULL,10241,3,'12:00','13:00',0);
insert into schedules values(NULL,10242,3,'12:00','13:00',0);
insert into schedules values(NULL,10244,3,'12:00','13:00',0);
insert into schedules values(NULL,10245,3,'12:00','13:00',0);
insert into schedules values(NULL,10247,3,'12:00','13:00',0);
insert into schedules values(NULL,10249,3,'12:00','13:00',0);
insert into schedules values(NULL,10251,3,'12:00','13:00',0);











insert into schedules values(NULL,10238,3,'13:00','14:00',0);
insert into schedules values(NULL,10239,3,'13:00','14:00',0);
insert into schedules values(NULL,10241,3,'13:00','14:00',0);
insert into schedules values(NULL,10242,3,'13:00','14:00',0);
insert into schedules values(NULL,10244,3,'13:00','14:00',0);
insert into schedules values(NULL,10245,3,'13:00','14:00',0);
insert into schedules values(NULL,10247,3,'13:00','14:00',0);
insert into schedules values(NULL,10249,3,'13:00','14:00',0);
insert into schedules values(NULL,10251,3,'13:00','14:00',0);











insert into schedules values(NULL,10238,3,'14:00','15:00',0);
insert into schedules values(NULL,10239,3,'14:00','15:00',0);
insert into schedules values(NULL,10241,3,'14:00','15:00',0);
insert into schedules values(NULL,10242,3,'14:00','15:00',0);
insert into schedules values(NULL,10244,3,'14:00','15:00',0);
insert into schedules values(NULL,10245,3,'14:00','15:00',0);
insert into schedules values(NULL,10247,3,'14:00','15:00',0);
insert into schedules values(NULL,10249,3,'14:00','15:00',0);
insert into schedules values(NULL,10251,3,'14:00','15:00',0);











insert into schedules values(NULL,10238,3,'15:00','16:00',0);
insert into schedules values(NULL,10239,3,'15:00','16:00',0);
insert into schedules values(NULL,10241,3,'15:00','16:00',0);
insert into schedules values(NULL,10242,3,'15:00','16:00',0);
insert into schedules values(NULL,10244,3,'15:00','16:00',0);
insert into schedules values(NULL,10245,3,'15:00','16:00',0);
insert into schedules values(NULL,10247,3,'15:00','16:00',0);
insert into schedules values(NULL,10249,3,'15:00','16:00',0);
insert into schedules values(NULL,10251,3,'15:00','16:00',0);











insert into schedules values(NULL,10238,3,'16:00','17:00',0);
insert into schedules values(NULL,10239,3,'16:00','17:00',0);
insert into schedules values(NULL,10241,3,'16:00','17:00',0);
insert into schedules values(NULL,10242,3,'16:00','17:00',0);
insert into schedules values(NULL,10244,3,'16:00','17:00',0);
insert into schedules values(NULL,10245,3,'16:00','17:00',0);
insert into schedules values(NULL,10247,3,'16:00','17:00',0);
insert into schedules values(NULL,10249,3,'16:00','17:00',0);
insert into schedules values(NULL,10251,3,'16:00','17:00',0);











insert into schedules values(NULL,10238,3,'17:00','18:00',0);
insert into schedules values(NULL,10239,3,'17:00','18:00',0);
insert into schedules values(NULL,10241,3,'17:00','18:00',0);
insert into schedules values(NULL,10242,3,'17:00','18:00',0);
insert into schedules values(NULL,10244,3,'17:00','18:00',0);
insert into schedules values(NULL,10245,3,'17:00','18:00',0);
insert into schedules values(NULL,10247,3,'17:00','18:00',0);
insert into schedules values(NULL,10249,3,'17:00','18:00',0);
insert into schedules values(NULL,10251,3,'17:00','18:00',0);











insert into schedules values(NULL,10238,3,'18:00','19:00',0);
insert into schedules values(NULL,10239,3,'18:00','19:00',0);
insert into schedules values(NULL,10241,3,'18:00','19:00',0);
insert into schedules values(NULL,10242,3,'18:00','19:00',0);
insert into schedules values(NULL,10244,3,'18:00','19:00',0);
insert into schedules values(NULL,10245,3,'18:00','19:00',0);
insert into schedules values(NULL,10247,3,'18:00','19:00',0);
insert into schedules values(NULL,10249,3,'18:00','19:00',0);
insert into schedules values(NULL,10251,3,'18:00','19:00',0);











insert into schedules values(NULL,10238,3,'19:00','20:00',0);
insert into schedules values(NULL,10239,3,'19:00','20:00',0);
insert into schedules values(NULL,10241,3,'19:00','20:00',0);
insert into schedules values(NULL,10242,3,'19:00','20:00',0);
insert into schedules values(NULL,10244,3,'19:00','20:00',0);
insert into schedules values(NULL,10245,3,'19:00','20:00',0);
insert into schedules values(NULL,10247,3,'19:00','20:00',0);
insert into schedules values(NULL,10249,3,'19:00','20:00',0);
insert into schedules values(NULL,10251,3,'19:00','20:00',0);











insert into schedules values(NULL,10238,3,'09:00','10:00',1);
insert into schedules values(NULL,10239,3,'09:00','10:00',1);
insert into schedules values(NULL,10241,3,'09:00','10:00',1);
insert into schedules values(NULL,10242,3,'09:00','10:00',1);
insert into schedules values(NULL,10244,3,'09:00','10:00',1);
insert into schedules values(NULL,10245,3,'09:00','10:00',1);
insert into schedules values(NULL,10247,3,'09:00','10:00',1);
insert into schedules values(NULL,10249,3,'09:00','10:00',1);
insert into schedules values(NULL,10251,3,'09:00','10:00',1);











insert into schedules values(NULL,10238,3,'10:00','11:00',1);
insert into schedules values(NULL,10239,3,'10:00','11:00',1);
insert into schedules values(NULL,10241,3,'10:00','11:00',1);
insert into schedules values(NULL,10242,3,'10:00','11:00',1);
insert into schedules values(NULL,10244,3,'10:00','11:00',1);
insert into schedules values(NULL,10245,3,'10:00','11:00',1);
insert into schedules values(NULL,10247,3,'10:00','11:00',1);
insert into schedules values(NULL,10249,3,'10:00','11:00',1);
insert into schedules values(NULL,10251,3,'10:00','11:00',1);











insert into schedules values(NULL,10238,3,'11:00','12:00',1);
insert into schedules values(NULL,10239,3,'11:00','12:00',1);
insert into schedules values(NULL,10241,3,'11:00','12:00',1);
insert into schedules values(NULL,10242,3,'11:00','12:00',1);
insert into schedules values(NULL,10244,3,'11:00','12:00',1);
insert into schedules values(NULL,10245,3,'11:00','12:00',1);
insert into schedules values(NULL,10247,3,'11:00','12:00',1);
insert into schedules values(NULL,10249,3,'11:00','12:00',1);
insert into schedules values(NULL,10251,3,'11:00','12:00',1);











insert into schedules values(NULL,10238,3,'12:00','13:00',1);
insert into schedules values(NULL,10239,3,'12:00','13:00',1);
insert into schedules values(NULL,10241,3,'12:00','13:00',1);
insert into schedules values(NULL,10242,3,'12:00','13:00',1);
insert into schedules values(NULL,10244,3,'12:00','13:00',1);
insert into schedules values(NULL,10245,3,'12:00','13:00',1);
insert into schedules values(NULL,10247,3,'12:00','13:00',1);
insert into schedules values(NULL,10249,3,'12:00','13:00',1);
insert into schedules values(NULL,10251,3,'12:00','13:00',1);











insert into schedules values(NULL,10238,3,'13:00','14:00',1);
insert into schedules values(NULL,10239,3,'13:00','14:00',1);
insert into schedules values(NULL,10241,3,'13:00','14:00',1);
insert into schedules values(NULL,10242,3,'13:00','14:00',1);
insert into schedules values(NULL,10244,3,'13:00','14:00',1);
insert into schedules values(NULL,10245,3,'13:00','14:00',1);
insert into schedules values(NULL,10247,3,'13:00','14:00',1);
insert into schedules values(NULL,10249,3,'13:00','14:00',1);
insert into schedules values(NULL,10251,3,'13:00','14:00',1);











insert into schedules values(NULL,10238,3,'14:00','15:00',1);
insert into schedules values(NULL,10239,3,'14:00','15:00',1);
insert into schedules values(NULL,10241,3,'14:00','15:00',1);
insert into schedules values(NULL,10242,3,'14:00','15:00',1);
insert into schedules values(NULL,10244,3,'14:00','15:00',1);
insert into schedules values(NULL,10245,3,'14:00','15:00',1);
insert into schedules values(NULL,10247,3,'14:00','15:00',1);
insert into schedules values(NULL,10249,3,'14:00','15:00',1);
insert into schedules values(NULL,10251,3,'14:00','15:00',1);











insert into schedules values(NULL,10238,3,'15:00','16:00',1);
insert into schedules values(NULL,10239,3,'15:00','16:00',1);
insert into schedules values(NULL,10241,3,'15:00','16:00',1);
insert into schedules values(NULL,10242,3,'15:00','16:00',1);
insert into schedules values(NULL,10244,3,'15:00','16:00',1);
insert into schedules values(NULL,10245,3,'15:00','16:00',1);
insert into schedules values(NULL,10247,3,'15:00','16:00',1);
insert into schedules values(NULL,10249,3,'15:00','16:00',1);
insert into schedules values(NULL,10251,3,'15:00','16:00',1);











insert into schedules values(NULL,10238,3,'16:00','17:00',1);
insert into schedules values(NULL,10239,3,'16:00','17:00',1);
insert into schedules values(NULL,10241,3,'16:00','17:00',1);
insert into schedules values(NULL,10242,3,'16:00','17:00',1);
insert into schedules values(NULL,10244,3,'16:00','17:00',1);
insert into schedules values(NULL,10245,3,'16:00','17:00',1);
insert into schedules values(NULL,10247,3,'16:00','17:00',1);
insert into schedules values(NULL,10249,3,'16:00','17:00',1);
insert into schedules values(NULL,10251,3,'16:00','17:00',1);











insert into schedules values(NULL,10238,3,'17:00','18:00',1);
insert into schedules values(NULL,10239,3,'17:00','18:00',1);
insert into schedules values(NULL,10241,3,'17:00','18:00',1);
insert into schedules values(NULL,10242,3,'17:00','18:00',1);
insert into schedules values(NULL,10244,3,'17:00','18:00',1);
insert into schedules values(NULL,10245,3,'17:00','18:00',1);
insert into schedules values(NULL,10247,3,'17:00','18:00',1);
insert into schedules values(NULL,10249,3,'17:00','18:00',1);
insert into schedules values(NULL,10251,3,'17:00','18:00',1);











insert into schedules values(NULL,10238,3,'18:00','19:00',1);
insert into schedules values(NULL,10239,3,'18:00','19:00',1);
insert into schedules values(NULL,10241,3,'18:00','19:00',1);
insert into schedules values(NULL,10242,3,'18:00','19:00',1);
insert into schedules values(NULL,10244,3,'18:00','19:00',1);
insert into schedules values(NULL,10245,3,'18:00','19:00',1);
insert into schedules values(NULL,10247,3,'18:00','19:00',1);
insert into schedules values(NULL,10249,3,'18:00','19:00',1);
insert into schedules values(NULL,10251,3,'18:00','19:00',1);











insert into schedules values(NULL,10238,3,'19:00','20:00',1);
insert into schedules values(NULL,10239,3,'19:00','20:00',1);
insert into schedules values(NULL,10241,3,'19:00','20:00',1);
insert into schedules values(NULL,10242,3,'19:00','20:00',1);
insert into schedules values(NULL,10244,3,'19:00','20:00',1);
insert into schedules values(NULL,10245,3,'19:00','20:00',1);
insert into schedules values(NULL,10247,3,'19:00','20:00',1);
insert into schedules values(NULL,10249,3,'19:00','20:00',1);
insert into schedules values(NULL,10251,3,'19:00','20:00',1);











insert into schedules values(NULL,10239,4,'09:00','10:00',0);
insert into schedules values(NULL,10241,4,'09:00','10:00',0);
insert into schedules values(NULL,10242,4,'09:00','10:00',0);
insert into schedules values(NULL,10244,4,'09:00','10:00',0);
insert into schedules values(NULL,10245,4,'09:00','10:00',0);
insert into schedules values(NULL,10247,4,'09:00','10:00',0);
insert into schedules values(NULL,10249,4,'09:00','10:00',0);
insert into schedules values(NULL,10251,4,'09:00','10:00',0);











insert into schedules values(NULL,10238,4,'10:00','11:00',0);
insert into schedules values(NULL,10239,4,'10:00','11:00',0);
insert into schedules values(NULL,10241,4,'10:00','11:00',0);
insert into schedules values(NULL,10242,4,'10:00','11:00',0);
insert into schedules values(NULL,10244,4,'10:00','11:00',0);
insert into schedules values(NULL,10245,4,'10:00','11:00',0);
insert into schedules values(NULL,10247,4,'10:00','11:00',0);
insert into schedules values(NULL,10249,4,'10:00','11:00',0);
insert into schedules values(NULL,10251,4,'10:00','11:00',0);











insert into schedules values(NULL,10238,4,'11:00','12:00',0);
insert into schedules values(NULL,10239,4,'11:00','12:00',0);
insert into schedules values(NULL,10241,4,'11:00','12:00',0);
insert into schedules values(NULL,10242,4,'11:00','12:00',0);
insert into schedules values(NULL,10244,4,'11:00','12:00',0);
insert into schedules values(NULL,10245,4,'11:00','12:00',0);
insert into schedules values(NULL,10247,4,'11:00','12:00',0);
insert into schedules values(NULL,10249,4,'11:00','12:00',0);
insert into schedules values(NULL,10251,4,'11:00','12:00',0);











insert into schedules values(NULL,10238,4,'12:00','13:00',0);
insert into schedules values(NULL,10239,4,'12:00','13:00',0);
insert into schedules values(NULL,10241,4,'12:00','13:00',0);
insert into schedules values(NULL,10242,4,'12:00','13:00',0);
insert into schedules values(NULL,10244,4,'12:00','13:00',0);
insert into schedules values(NULL,10245,4,'12:00','13:00',0);
insert into schedules values(NULL,10247,4,'12:00','13:00',0);
insert into schedules values(NULL,10249,4,'12:00','13:00',0);
insert into schedules values(NULL,10251,4,'12:00','13:00',0);











insert into schedules values(NULL,10238,4,'13:00','14:00',0);
insert into schedules values(NULL,10239,4,'13:00','14:00',0);
insert into schedules values(NULL,10241,4,'13:00','14:00',0);
insert into schedules values(NULL,10242,4,'13:00','14:00',0);
insert into schedules values(NULL,10244,4,'13:00','14:00',0);
insert into schedules values(NULL,10245,4,'13:00','14:00',0);
insert into schedules values(NULL,10247,4,'13:00','14:00',0);
insert into schedules values(NULL,10249,4,'13:00','14:00',0);
insert into schedules values(NULL,10251,4,'13:00','14:00',0);











insert into schedules values(NULL,10238,4,'14:00','15:00',0);
insert into schedules values(NULL,10239,4,'14:00','15:00',0);
insert into schedules values(NULL,10241,4,'14:00','15:00',0);
insert into schedules values(NULL,10242,4,'14:00','15:00',0);
insert into schedules values(NULL,10244,4,'14:00','15:00',0);
insert into schedules values(NULL,10245,4,'14:00','15:00',0);
insert into schedules values(NULL,10247,4,'14:00','15:00',0);
insert into schedules values(NULL,10249,4,'14:00','15:00',0);
insert into schedules values(NULL,10251,4,'14:00','15:00',0);











insert into schedules values(NULL,10238,4,'15:00','16:00',0);
insert into schedules values(NULL,10239,4,'15:00','16:00',0);
insert into schedules values(NULL,10241,4,'15:00','16:00',0);
insert into schedules values(NULL,10242,4,'15:00','16:00',0);
insert into schedules values(NULL,10244,4,'15:00','16:00',0);
insert into schedules values(NULL,10245,4,'15:00','16:00',0);
insert into schedules values(NULL,10247,4,'15:00','16:00',0);
insert into schedules values(NULL,10249,4,'15:00','16:00',0);
insert into schedules values(NULL,10251,4,'15:00','16:00',0);











insert into schedules values(NULL,10238,4,'16:00','17:00',0);
insert into schedules values(NULL,10239,4,'16:00','17:00',0);
insert into schedules values(NULL,10241,4,'16:00','17:00',0);
insert into schedules values(NULL,10242,4,'16:00','17:00',0);
insert into schedules values(NULL,10244,4,'16:00','17:00',0);
insert into schedules values(NULL,10245,4,'16:00','17:00',0);
insert into schedules values(NULL,10247,4,'16:00','17:00',0);
insert into schedules values(NULL,10249,4,'16:00','17:00',0);
insert into schedules values(NULL,10251,4,'16:00','17:00',0);











insert into schedules values(NULL,10238,4,'17:00','18:00',0);
insert into schedules values(NULL,10239,4,'17:00','18:00',0);
insert into schedules values(NULL,10241,4,'17:00','18:00',0);
insert into schedules values(NULL,10242,4,'17:00','18:00',0);
insert into schedules values(NULL,10244,4,'17:00','18:00',0);
insert into schedules values(NULL,10245,4,'17:00','18:00',0);
insert into schedules values(NULL,10247,4,'17:00','18:00',0);
insert into schedules values(NULL,10249,4,'17:00','18:00',0);
insert into schedules values(NULL,10251,4,'17:00','18:00',0);











insert into schedules values(NULL,10238,4,'18:00','19:00',0);
insert into schedules values(NULL,10239,4,'18:00','19:00',0);
insert into schedules values(NULL,10241,4,'18:00','19:00',0);
insert into schedules values(NULL,10242,4,'18:00','19:00',0);
insert into schedules values(NULL,10244,4,'18:00','19:00',0);
insert into schedules values(NULL,10245,4,'18:00','19:00',0);
insert into schedules values(NULL,10247,4,'18:00','19:00',0);
insert into schedules values(NULL,10249,4,'18:00','19:00',0);
insert into schedules values(NULL,10251,4,'18:00','19:00',0);











insert into schedules values(NULL,10238,4,'19:00','20:00',0);
insert into schedules values(NULL,10239,4,'19:00','20:00',0);
insert into schedules values(NULL,10241,4,'19:00','20:00',0);
insert into schedules values(NULL,10242,4,'19:00','20:00',0);
insert into schedules values(NULL,10244,4,'19:00','20:00',0);
insert into schedules values(NULL,10245,4,'19:00','20:00',0);
insert into schedules values(NULL,10247,4,'19:00','20:00',0);
insert into schedules values(NULL,10249,4,'19:00','20:00',0);
insert into schedules values(NULL,10251,4,'19:00','20:00',0);











insert into schedules values(NULL,10238,4,'09:00','10:00',1);
insert into schedules values(NULL,10239,4,'09:00','10:00',1);
insert into schedules values(NULL,10241,4,'09:00','10:00',1);
insert into schedules values(NULL,10242,4,'09:00','10:00',1);
insert into schedules values(NULL,10244,4,'09:00','10:00',1);
insert into schedules values(NULL,10245,4,'09:00','10:00',1);
insert into schedules values(NULL,10247,4,'09:00','10:00',1);
insert into schedules values(NULL,10249,4,'09:00','10:00',1);
insert into schedules values(NULL,10251,4,'09:00','10:00',1);











insert into schedules values(NULL,10238,4,'10:00','11:00',1);
insert into schedules values(NULL,10239,4,'10:00','11:00',1);
insert into schedules values(NULL,10241,4,'10:00','11:00',1);
insert into schedules values(NULL,10242,4,'10:00','11:00',1);
insert into schedules values(NULL,10244,4,'10:00','11:00',1);
insert into schedules values(NULL,10245,4,'10:00','11:00',1);
insert into schedules values(NULL,10247,4,'10:00','11:00',1);
insert into schedules values(NULL,10249,4,'10:00','11:00',1);
insert into schedules values(NULL,10251,4,'10:00','11:00',1);











insert into schedules values(NULL,10238,4,'11:00','12:00',1);
insert into schedules values(NULL,10239,4,'11:00','12:00',1);
insert into schedules values(NULL,10241,4,'11:00','12:00',1);
insert into schedules values(NULL,10242,4,'11:00','12:00',1);
insert into schedules values(NULL,10244,4,'11:00','12:00',1);
insert into schedules values(NULL,10245,4,'11:00','12:00',1);
insert into schedules values(NULL,10247,4,'11:00','12:00',1);
insert into schedules values(NULL,10249,4,'11:00','12:00',1);
insert into schedules values(NULL,10251,4,'11:00','12:00',1);











insert into schedules values(NULL,10238,4,'12:00','13:00',1);
insert into schedules values(NULL,10239,4,'12:00','13:00',1);
insert into schedules values(NULL,10241,4,'12:00','13:00',1);
insert into schedules values(NULL,10242,4,'12:00','13:00',1);
insert into schedules values(NULL,10244,4,'12:00','13:00',1);
insert into schedules values(NULL,10245,4,'12:00','13:00',1);
insert into schedules values(NULL,10247,4,'12:00','13:00',1);
insert into schedules values(NULL,10249,4,'12:00','13:00',1);
insert into schedules values(NULL,10251,4,'12:00','13:00',1);











insert into schedules values(NULL,10238,4,'13:00','14:00',1);
insert into schedules values(NULL,10239,4,'13:00','14:00',1);
insert into schedules values(NULL,10241,4,'13:00','14:00',1);
insert into schedules values(NULL,10242,4,'13:00','14:00',1);
insert into schedules values(NULL,10244,4,'13:00','14:00',1);
insert into schedules values(NULL,10245,4,'13:00','14:00',1);
insert into schedules values(NULL,10247,4,'13:00','14:00',1);
insert into schedules values(NULL,10249,4,'13:00','14:00',1);
insert into schedules values(NULL,10251,4,'13:00','14:00',1);











insert into schedules values(NULL,10238,4,'14:00','15:00',1);
insert into schedules values(NULL,10239,4,'14:00','15:00',1);
insert into schedules values(NULL,10241,4,'14:00','15:00',1);
insert into schedules values(NULL,10242,4,'14:00','15:00',1);
insert into schedules values(NULL,10244,4,'14:00','15:00',1);
insert into schedules values(NULL,10245,4,'14:00','15:00',1);
insert into schedules values(NULL,10247,4,'14:00','15:00',1);
insert into schedules values(NULL,10249,4,'14:00','15:00',1);
insert into schedules values(NULL,10251,4,'14:00','15:00',1);











insert into schedules values(NULL,10238,4,'15:00','16:00',1);
insert into schedules values(NULL,10239,4,'15:00','16:00',1);
insert into schedules values(NULL,10241,4,'15:00','16:00',1);
insert into schedules values(NULL,10242,4,'15:00','16:00',1);
insert into schedules values(NULL,10244,4,'15:00','16:00',1);
insert into schedules values(NULL,10245,4,'15:00','16:00',1);
insert into schedules values(NULL,10247,4,'15:00','16:00',1);
insert into schedules values(NULL,10249,4,'15:00','16:00',1);
insert into schedules values(NULL,10251,4,'15:00','16:00',1);











insert into schedules values(NULL,10238,4,'16:00','17:00',1);
insert into schedules values(NULL,10239,4,'16:00','17:00',1);
insert into schedules values(NULL,10241,4,'16:00','17:00',1);
insert into schedules values(NULL,10242,4,'16:00','17:00',1);
insert into schedules values(NULL,10244,4,'16:00','17:00',1);
insert into schedules values(NULL,10245,4,'16:00','17:00',1);
insert into schedules values(NULL,10247,4,'16:00','17:00',1);
insert into schedules values(NULL,10249,4,'16:00','17:00',1);
insert into schedules values(NULL,10251,4,'16:00','17:00',1);











insert into schedules values(NULL,10238,4,'17:00','18:00',1);
insert into schedules values(NULL,10239,4,'17:00','18:00',1);
insert into schedules values(NULL,10241,4,'17:00','18:00',1);
insert into schedules values(NULL,10242,4,'17:00','18:00',1);
insert into schedules values(NULL,10244,4,'17:00','18:00',1);
insert into schedules values(NULL,10245,4,'17:00','18:00',1);
insert into schedules values(NULL,10247,4,'17:00','18:00',1);
insert into schedules values(NULL,10249,4,'17:00','18:00',1);
insert into schedules values(NULL,10251,4,'17:00','18:00',1);











insert into schedules values(NULL,10238,4,'18:00','19:00',1);
insert into schedules values(NULL,10239,4,'18:00','19:00',1);
insert into schedules values(NULL,10241,4,'18:00','19:00',1);
insert into schedules values(NULL,10242,4,'18:00','19:00',1);
insert into schedules values(NULL,10244,4,'18:00','19:00',1);
insert into schedules values(NULL,10245,4,'18:00','19:00',1);
insert into schedules values(NULL,10247,4,'18:00','19:00',1);
insert into schedules values(NULL,10249,4,'18:00','19:00',1);
insert into schedules values(NULL,10251,4,'18:00','19:00',1);











insert into schedules values(NULL,10238,4,'19:00','20:00',1);
insert into schedules values(NULL,10239,4,'19:00','20:00',1);
insert into schedules values(NULL,10241,4,'19:00','20:00',1);
insert into schedules values(NULL,10242,4,'19:00','20:00',1);
insert into schedules values(NULL,10244,4,'19:00','20:00',1);
insert into schedules values(NULL,10245,4,'19:00','20:00',1);
insert into schedules values(NULL,10247,4,'19:00','20:00',1);
insert into schedules values(NULL,10249,4,'19:00','20:00',1);
insert into schedules values(NULL,10251,4,'19:00','20:00',1);











insert into schedules values(NULL,10239,5,'09:00','10:00',0);
insert into schedules values(NULL,10241,5,'09:00','10:00',0);
insert into schedules values(NULL,10242,5,'09:00','10:00',0);
insert into schedules values(NULL,10244,5,'09:00','10:00',0);
insert into schedules values(NULL,10245,5,'09:00','10:00',0);
insert into schedules values(NULL,10247,5,'09:00','10:00',0);
insert into schedules values(NULL,10249,5,'09:00','10:00',0);
insert into schedules values(NULL,10251,5,'09:00','10:00',0);











insert into schedules values(NULL,10238,5,'10:00','11:00',0);
insert into schedules values(NULL,10239,5,'10:00','11:00',0);
insert into schedules values(NULL,10241,5,'10:00','11:00',0);
insert into schedules values(NULL,10242,5,'10:00','11:00',0);
insert into schedules values(NULL,10244,5,'10:00','11:00',0);
insert into schedules values(NULL,10245,5,'10:00','11:00',0);
insert into schedules values(NULL,10247,5,'10:00','11:00',0);
insert into schedules values(NULL,10249,5,'10:00','11:00',0);
insert into schedules values(NULL,10251,5,'10:00','11:00',0);











insert into schedules values(NULL,10238,5,'11:00','12:00',0);
insert into schedules values(NULL,10239,5,'11:00','12:00',0);
insert into schedules values(NULL,10241,5,'11:00','12:00',0);
insert into schedules values(NULL,10242,5,'11:00','12:00',0);
insert into schedules values(NULL,10244,5,'11:00','12:00',0);
insert into schedules values(NULL,10245,5,'11:00','12:00',0);
insert into schedules values(NULL,10247,5,'11:00','12:00',0);
insert into schedules values(NULL,10249,5,'11:00','12:00',0);
insert into schedules values(NULL,10251,5,'11:00','12:00',0);











insert into schedules values(NULL,10238,5,'12:00','13:00',0);
insert into schedules values(NULL,10239,5,'12:00','13:00',0);
insert into schedules values(NULL,10241,5,'12:00','13:00',0);
insert into schedules values(NULL,10242,5,'12:00','13:00',0);
insert into schedules values(NULL,10244,5,'12:00','13:00',0);
insert into schedules values(NULL,10245,5,'12:00','13:00',0);
insert into schedules values(NULL,10247,5,'12:00','13:00',0);
insert into schedules values(NULL,10249,5,'12:00','13:00',0);
insert into schedules values(NULL,10251,5,'12:00','13:00',0);











insert into schedules values(NULL,10238,5,'13:00','14:00',0);
insert into schedules values(NULL,10239,5,'13:00','14:00',0);
insert into schedules values(NULL,10241,5,'13:00','14:00',0);
insert into schedules values(NULL,10242,5,'13:00','14:00',0);
insert into schedules values(NULL,10244,5,'13:00','14:00',0);
insert into schedules values(NULL,10245,5,'13:00','14:00',0);
insert into schedules values(NULL,10247,5,'13:00','14:00',0);
insert into schedules values(NULL,10249,5,'13:00','14:00',0);
insert into schedules values(NULL,10251,5,'13:00','14:00',0);











insert into schedules values(NULL,10238,5,'14:00','15:00',0);
insert into schedules values(NULL,10239,5,'14:00','15:00',0);
insert into schedules values(NULL,10241,5,'14:00','15:00',0);
insert into schedules values(NULL,10242,5,'14:00','15:00',0);
insert into schedules values(NULL,10244,5,'14:00','15:00',0);
insert into schedules values(NULL,10245,5,'14:00','15:00',0);
insert into schedules values(NULL,10247,5,'14:00','15:00',0);
insert into schedules values(NULL,10249,5,'14:00','15:00',0);
insert into schedules values(NULL,10251,5,'14:00','15:00',0);











insert into schedules values(NULL,10238,5,'15:00','16:00',0);
insert into schedules values(NULL,10239,5,'15:00','16:00',0);
insert into schedules values(NULL,10241,5,'15:00','16:00',0);
insert into schedules values(NULL,10242,5,'15:00','16:00',0);
insert into schedules values(NULL,10244,5,'15:00','16:00',0);
insert into schedules values(NULL,10245,5,'15:00','16:00',0);
insert into schedules values(NULL,10247,5,'15:00','16:00',0);
insert into schedules values(NULL,10249,5,'15:00','16:00',0);
insert into schedules values(NULL,10251,5,'15:00','16:00',0);











insert into schedules values(NULL,10238,5,'16:00','17:00',0);
insert into schedules values(NULL,10239,5,'16:00','17:00',0);
insert into schedules values(NULL,10241,5,'16:00','17:00',0);
insert into schedules values(NULL,10242,5,'16:00','17:00',0);
insert into schedules values(NULL,10244,5,'16:00','17:00',0);
insert into schedules values(NULL,10245,5,'16:00','17:00',0);
insert into schedules values(NULL,10247,5,'16:00','17:00',0);
insert into schedules values(NULL,10249,5,'16:00','17:00',0);
insert into schedules values(NULL,10251,5,'16:00','17:00',0);











insert into schedules values(NULL,10238,5,'17:00','18:00',0);
insert into schedules values(NULL,10239,5,'17:00','18:00',0);
insert into schedules values(NULL,10241,5,'17:00','18:00',0);
insert into schedules values(NULL,10242,5,'17:00','18:00',0);
insert into schedules values(NULL,10244,5,'17:00','18:00',0);
insert into schedules values(NULL,10245,5,'17:00','18:00',0);
insert into schedules values(NULL,10247,5,'17:00','18:00',0);
insert into schedules values(NULL,10249,5,'17:00','18:00',0);
insert into schedules values(NULL,10251,5,'17:00','18:00',0);











insert into schedules values(NULL,10238,5,'18:00','19:00',0);
insert into schedules values(NULL,10239,5,'18:00','19:00',0);
insert into schedules values(NULL,10241,5,'18:00','19:00',0);
insert into schedules values(NULL,10242,5,'18:00','19:00',0);
insert into schedules values(NULL,10244,5,'18:00','19:00',0);
insert into schedules values(NULL,10245,5,'18:00','19:00',0);
insert into schedules values(NULL,10247,5,'18:00','19:00',0);
insert into schedules values(NULL,10249,5,'18:00','19:00',0);
insert into schedules values(NULL,10251,5,'18:00','19:00',0);











insert into schedules values(NULL,10238,5,'19:00','20:00',0);
insert into schedules values(NULL,10239,5,'19:00','20:00',0);
insert into schedules values(NULL,10241,5,'19:00','20:00',0);
insert into schedules values(NULL,10242,5,'19:00','20:00',0);
insert into schedules values(NULL,10244,5,'19:00','20:00',0);
insert into schedules values(NULL,10245,5,'19:00','20:00',0);
insert into schedules values(NULL,10247,5,'19:00','20:00',0);
insert into schedules values(NULL,10249,5,'19:00','20:00',0);
insert into schedules values(NULL,10251,5,'19:00','20:00',0);











insert into schedules values(NULL,10238,5,'09:00','10:00',1);
insert into schedules values(NULL,10239,5,'09:00','10:00',1);
insert into schedules values(NULL,10241,5,'09:00','10:00',1);
insert into schedules values(NULL,10242,5,'09:00','10:00',1);
insert into schedules values(NULL,10244,5,'09:00','10:00',1);
insert into schedules values(NULL,10245,5,'09:00','10:00',1);
insert into schedules values(NULL,10247,5,'09:00','10:00',1);
insert into schedules values(NULL,10249,5,'09:00','10:00',1);
insert into schedules values(NULL,10251,5,'09:00','10:00',1);











insert into schedules values(NULL,10238,5,'10:00','11:00',1);
insert into schedules values(NULL,10239,5,'10:00','11:00',1);
insert into schedules values(NULL,10241,5,'10:00','11:00',1);
insert into schedules values(NULL,10242,5,'10:00','11:00',1);
insert into schedules values(NULL,10244,5,'10:00','11:00',1);
insert into schedules values(NULL,10245,5,'10:00','11:00',1);
insert into schedules values(NULL,10247,5,'10:00','11:00',1);
insert into schedules values(NULL,10249,5,'10:00','11:00',1);
insert into schedules values(NULL,10251,5,'10:00','11:00',1);











insert into schedules values(NULL,10238,5,'11:00','12:00',1);
insert into schedules values(NULL,10239,5,'11:00','12:00',1);
insert into schedules values(NULL,10241,5,'11:00','12:00',1);
insert into schedules values(NULL,10242,5,'11:00','12:00',1);
insert into schedules values(NULL,10244,5,'11:00','12:00',1);
insert into schedules values(NULL,10245,5,'11:00','12:00',1);
insert into schedules values(NULL,10247,5,'11:00','12:00',1);
insert into schedules values(NULL,10249,5,'11:00','12:00',1);
insert into schedules values(NULL,10251,5,'11:00','12:00',1);











insert into schedules values(NULL,10238,5,'12:00','13:00',1);
insert into schedules values(NULL,10239,5,'12:00','13:00',1);
insert into schedules values(NULL,10241,5,'12:00','13:00',1);
insert into schedules values(NULL,10242,5,'12:00','13:00',1);
insert into schedules values(NULL,10244,5,'12:00','13:00',1);
insert into schedules values(NULL,10245,5,'12:00','13:00',1);
insert into schedules values(NULL,10247,5,'12:00','13:00',1);
insert into schedules values(NULL,10249,5,'12:00','13:00',1);
insert into schedules values(NULL,10251,5,'12:00','13:00',1);











insert into schedules values(NULL,10238,5,'13:00','14:00',1);
insert into schedules values(NULL,10239,5,'13:00','14:00',1);
insert into schedules values(NULL,10241,5,'13:00','14:00',1);
insert into schedules values(NULL,10242,5,'13:00','14:00',1);
insert into schedules values(NULL,10244,5,'13:00','14:00',1);
insert into schedules values(NULL,10245,5,'13:00','14:00',1);
insert into schedules values(NULL,10247,5,'13:00','14:00',1);
insert into schedules values(NULL,10249,5,'13:00','14:00',1);
insert into schedules values(NULL,10251,5,'13:00','14:00',1);











insert into schedules values(NULL,10238,5,'14:00','15:00',1);
insert into schedules values(NULL,10239,5,'14:00','15:00',1);
insert into schedules values(NULL,10241,5,'14:00','15:00',1);
insert into schedules values(NULL,10242,5,'14:00','15:00',1);
insert into schedules values(NULL,10244,5,'14:00','15:00',1);
insert into schedules values(NULL,10245,5,'14:00','15:00',1);
insert into schedules values(NULL,10247,5,'14:00','15:00',1);
insert into schedules values(NULL,10249,5,'14:00','15:00',1);
insert into schedules values(NULL,10251,5,'14:00','15:00',1);











insert into schedules values(NULL,10238,5,'15:00','16:00',1);
insert into schedules values(NULL,10239,5,'15:00','16:00',1);
insert into schedules values(NULL,10241,5,'15:00','16:00',1);
insert into schedules values(NULL,10242,5,'15:00','16:00',1);
insert into schedules values(NULL,10244,5,'15:00','16:00',1);
insert into schedules values(NULL,10245,5,'15:00','16:00',1);
insert into schedules values(NULL,10247,5,'15:00','16:00',1);
insert into schedules values(NULL,10249,5,'15:00','16:00',1);
insert into schedules values(NULL,10251,5,'15:00','16:00',1);











insert into schedules values(NULL,10238,5,'16:00','17:00',1);
insert into schedules values(NULL,10239,5,'16:00','17:00',1);
insert into schedules values(NULL,10241,5,'16:00','17:00',1);
insert into schedules values(NULL,10242,5,'16:00','17:00',1);
insert into schedules values(NULL,10244,5,'16:00','17:00',1);
insert into schedules values(NULL,10245,5,'16:00','17:00',1);
insert into schedules values(NULL,10247,5,'16:00','17:00',1);
insert into schedules values(NULL,10249,5,'16:00','17:00',1);
insert into schedules values(NULL,10251,5,'16:00','17:00',1);











insert into schedules values(NULL,10238,5,'17:00','18:00',1);
insert into schedules values(NULL,10239,5,'17:00','18:00',1);
insert into schedules values(NULL,10241,5,'17:00','18:00',1);
insert into schedules values(NULL,10242,5,'17:00','18:00',1);
insert into schedules values(NULL,10244,5,'17:00','18:00',1);
insert into schedules values(NULL,10245,5,'17:00','18:00',1);
insert into schedules values(NULL,10247,5,'17:00','18:00',1);
insert into schedules values(NULL,10249,5,'17:00','18:00',1);
insert into schedules values(NULL,10251,5,'17:00','18:00',1);











insert into schedules values(NULL,10238,5,'18:00','19:00',1);
insert into schedules values(NULL,10239,5,'18:00','19:00',1);
insert into schedules values(NULL,10241,5,'18:00','19:00',1);
insert into schedules values(NULL,10242,5,'18:00','19:00',1);
insert into schedules values(NULL,10244,5,'18:00','19:00',1);
insert into schedules values(NULL,10245,5,'18:00','19:00',1);
insert into schedules values(NULL,10247,5,'18:00','19:00',1);
insert into schedules values(NULL,10249,5,'18:00','19:00',1);
insert into schedules values(NULL,10251,5,'18:00','19:00',1);











insert into schedules values(NULL,10238,5,'19:00','20:00',1);
insert into schedules values(NULL,10239,5,'19:00','20:00',1);
insert into schedules values(NULL,10241,5,'19:00','20:00',1);
insert into schedules values(NULL,10242,5,'19:00','20:00',1);
insert into schedules values(NULL,10244,5,'19:00','20:00',1);
insert into schedules values(NULL,10245,5,'19:00','20:00',1);
insert into schedules values(NULL,10247,5,'19:00','20:00',1);
insert into schedules values(NULL,10249,5,'19:00','20:00',1);
insert into schedules values(NULL,10251,5,'19:00','20:00',1);











insert into schedules values(NULL,10238,6,'10:00','12:00',1);
insert into schedules values(NULL,10239,6,'10:00','12:00',1);
insert into schedules values(NULL,10241,6,'10:00','12:00',1);
insert into schedules values(NULL,10242,6,'10:00','12:00',1);
insert into schedules values(NULL,10244,6,'10:00','12:00',1);
insert into schedules values(NULL,10245,6,'10:00','12:00',1);
insert into schedules values(NULL,10247,6,'10:00','12:00',1);
insert into schedules values(NULL,10249,6,'10:00','12:00',1);
insert into schedules values(NULL,10251,6,'10:00','12:00',1);
insert into schedules values(NULL,10238,6,'10:00','12:00',0);
insert into schedules values(NULL,10239,6,'10:00','12:00',0);
insert into schedules values(NULL,10241,6,'10:00','12:00',0);
insert into schedules values(NULL,10242,6,'10:00','12:00',0);
insert into schedules values(NULL,10244,6,'10:00','12:00',0);
insert into schedules values(NULL,10245,6,'10:00','12:00',0);
insert into schedules values(NULL,10247,6,'10:00','12:00',0);
insert into schedules values(NULL,10249,6,'10:00','12:00',0);
insert into schedules values(NULL,10251,6,'10:00','12:00',0);
insert into schedules values(NULL,10238,6,'12:00','14:00',1);
insert into schedules values(NULL,10239,6,'12:00','14:00',1);
insert into schedules values(NULL,10241,6,'12:00','14:00',1);
insert into schedules values(NULL,10242,6,'12:00','14:00',1);
insert into schedules values(NULL,10244,6,'12:00','14:00',1);
insert into schedules values(NULL,10245,6,'12:00','14:00',1);
insert into schedules values(NULL,10247,6,'12:00','14:00',1);
insert into schedules values(NULL,10249,6,'12:00','14:00',1);
insert into schedules values(NULL,10251,6,'12:00','14:00',1);
insert into schedules values(NULL,10238,6,'12:00','14:00',0);
insert into schedules values(NULL,10239,6,'12:00','14:00',0);
insert into schedules values(NULL,10241,6,'12:00','14:00',0);
insert into schedules values(NULL,10242,6,'12:00','14:00',0);
insert into schedules values(NULL,10244,6,'12:00','14:00',0);
insert into schedules values(NULL,10245,6,'12:00','14:00',0);
insert into schedules values(NULL,10247,6,'12:00','14:00',0);
insert into schedules values(NULL,10249,6,'12:00','14:00',0);
insert into schedules values(NULL,10251,6,'12:00','14:00',0);
insert into schedules values(NULL,10238,6,'14:00','16:00',1);
insert into schedules values(NULL,10239,6,'14:00','16:00',1);
insert into schedules values(NULL,10241,6,'14:00','16:00',1);
insert into schedules values(NULL,10242,6,'14:00','16:00',1);
insert into schedules values(NULL,10244,6,'14:00','16:00',1);
insert into schedules values(NULL,10245,6,'14:00','16:00',1);
insert into schedules values(NULL,10247,6,'14:00','16:00',1);
insert into schedules values(NULL,10249,6,'14:00','16:00',1);
insert into schedules values(NULL,10251,6,'14:00','16:00',1);
insert into schedules values(NULL,10238,6,'14:00','16:00',0);
insert into schedules values(NULL,10239,6,'14:00','16:00',0);
insert into schedules values(NULL,10241,6,'14:00','16:00',0);
insert into schedules values(NULL,10242,6,'14:00','16:00',0);
insert into schedules values(NULL,10244,6,'14:00','16:00',0);
insert into schedules values(NULL,10245,6,'14:00','16:00',0);
insert into schedules values(NULL,10247,6,'14:00','16:00',0);
insert into schedules values(NULL,10249,6,'14:00','16:00',0);
insert into schedules values(NULL,10251,6,'14:00','16:00',0);
insert into schedules values(NULL,10238,6,'16:00','18:00',1);
insert into schedules values(NULL,10239,6,'16:00','18:00',1);
insert into schedules values(NULL,10241,6,'16:00','18:00',1);
insert into schedules values(NULL,10242,6,'16:00','18:00',1);
insert into schedules values(NULL,10244,6,'16:00','18:00',1);
insert into schedules values(NULL,10245,6,'16:00','18:00',1);
insert into schedules values(NULL,10247,6,'16:00','18:00',1);
insert into schedules values(NULL,10249,6,'16:00','18:00',1);
insert into schedules values(NULL,10251,6,'16:00','18:00',1);
insert into schedules values(NULL,10238,6,'16:00','18:00',0);
insert into schedules values(NULL,10239,6,'16:00','18:00',0);
insert into schedules values(NULL,10241,6,'16:00','18:00',0);
insert into schedules values(NULL,10242,6,'16:00','18:00',0);
insert into schedules values(NULL,10244,6,'16:00','18:00',0);
insert into schedules values(NULL,10245,6,'16:00','18:00',0);
insert into schedules values(NULL,10247,6,'16:00','18:00',0);
insert into schedules values(NULL,10249,6,'16:00','18:00',0);
insert into schedules values(NULL,10251,6,'16:00','18:00',0);
insert into schedules values(NULL,10238,7,'10:00','12:00',1);
insert into schedules values(NULL,10239,7,'10:00','12:00',1);
insert into schedules values(NULL,10241,7,'10:00','12:00',1);
insert into schedules values(NULL,10242,7,'10:00','12:00',1);
insert into schedules values(NULL,10244,7,'10:00','12:00',1);
insert into schedules values(NULL,10245,7,'10:00','12:00',1);
insert into schedules values(NULL,10247,7,'10:00','12:00',1);
insert into schedules values(NULL,10249,7,'10:00','12:00',1);
insert into schedules values(NULL,10251,7,'10:00','12:00',1);
insert into schedules values(NULL,10238,7,'10:00','12:00',0);
insert into schedules values(NULL,10239,7,'10:00','12:00',0);
insert into schedules values(NULL,10241,7,'10:00','12:00',0);
insert into schedules values(NULL,10242,7,'10:00','12:00',0);
insert into schedules values(NULL,10244,7,'10:00','12:00',0);
insert into schedules values(NULL,10245,7,'10:00','12:00',0);
insert into schedules values(NULL,10247,7,'10:00','12:00',0);
insert into schedules values(NULL,10249,7,'10:00','12:00',0);
insert into schedules values(NULL,10251,7,'10:00','12:00',0);
insert into schedules values(NULL,10238,7,'12:00','14:00',1);
insert into schedules values(NULL,10239,7,'12:00','14:00',1);
insert into schedules values(NULL,10241,7,'12:00','14:00',1);
insert into schedules values(NULL,10242,7,'12:00','14:00',1);
insert into schedules values(NULL,10244,7,'12:00','14:00',1);
insert into schedules values(NULL,10245,7,'12:00','14:00',1);
insert into schedules values(NULL,10247,7,'12:00','14:00',1);
insert into schedules values(NULL,10249,7,'12:00','14:00',1);
insert into schedules values(NULL,10251,7,'12:00','14:00',1);
insert into schedules values(NULL,10238,7,'12:00','14:00',0);
insert into schedules values(NULL,10239,7,'12:00','14:00',0);
insert into schedules values(NULL,10241,7,'12:00','14:00',0);
insert into schedules values(NULL,10242,7,'12:00','14:00',0);
insert into schedules values(NULL,10244,7,'12:00','14:00',0);
insert into schedules values(NULL,10245,7,'12:00','14:00',0);
insert into schedules values(NULL,10247,7,'12:00','14:00',0);
insert into schedules values(NULL,10249,7,'12:00','14:00',0);
insert into schedules values(NULL,10251,7,'12:00','14:00',0);
insert into schedules values(NULL,10238,7,'14:00','16:00',1);
insert into schedules values(NULL,10239,7,'14:00','16:00',1);
insert into schedules values(NULL,10241,7,'14:00','16:00',1);
insert into schedules values(NULL,10242,7,'14:00','16:00',1);
insert into schedules values(NULL,10244,7,'14:00','16:00',1);
insert into schedules values(NULL,10245,7,'14:00','16:00',1);
insert into schedules values(NULL,10247,7,'14:00','16:00',1);
insert into schedules values(NULL,10249,7,'14:00','16:00',1);
insert into schedules values(NULL,10251,7,'14:00','16:00',1);
insert into schedules values(NULL,10238,7,'14:00','16:00',0);
insert into schedules values(NULL,10239,7,'14:00','16:00',0);
insert into schedules values(NULL,10241,7,'14:00','16:00',0);
insert into schedules values(NULL,10242,7,'14:00','16:00',0);
insert into schedules values(NULL,10244,7,'14:00','16:00',0);
insert into schedules values(NULL,10245,7,'14:00','16:00',0);
insert into schedules values(NULL,10247,7,'14:00','16:00',0);
insert into schedules values(NULL,10249,7,'14:00','16:00',0);
insert into schedules values(NULL,10251,7,'14:00','16:00',0);
insert into schedules values(NULL,10238,7,'16:00','18:00',1);
insert into schedules values(NULL,10239,7,'16:00','18:00',1);
insert into schedules values(NULL,10241,7,'16:00','18:00',1);
insert into schedules values(NULL,10242,7,'16:00','18:00',1);
insert into schedules values(NULL,10244,7,'16:00','18:00',1);
insert into schedules values(NULL,10245,7,'16:00','18:00',1);
insert into schedules values(NULL,10247,7,'16:00','18:00',1);
insert into schedules values(NULL,10249,7,'16:00','18:00',1);
insert into schedules values(NULL,10251,7,'16:00','18:00',1);
insert into schedules values(NULL,10238,7,'16:00','18:00',0);
insert into schedules values(NULL,10239,7,'16:00','18:00',0);
insert into schedules values(NULL,10241,7,'16:00','18:00',0);
insert into schedules values(NULL,10242,7,'16:00','18:00',0);
insert into schedules values(NULL,10244,7,'16:00','18:00',0);
insert into schedules values(NULL,10245,7,'16:00','18:00',0);
insert into schedules values(NULL,10247,7,'16:00','18:00',0);
insert into schedules values(NULL,10249,7,'16:00','18:00',0);
insert into schedules values(NULL,10251,7,'16:00','18:00',0);
insert into schedules values(NULL,10238,1,'09:00','10:00',0);
insert into schedules values(NULL,10239,1,'09:00','10:00',0);
insert into schedules values(NULL,10241,1,'09:00','10:00',0);
insert into schedules values(NULL,10242,1,'09:00','10:00',0);
insert into schedules values(NULL,10244,1,'09:00','10:00',0);
insert into schedules values(NULL,10245,1,'09:00','10:00',0);
insert into schedules values(NULL,10247,1,'09:00','10:00',0);
insert into schedules values(NULL,10249,1,'09:00','10:00',0);
insert into schedules values(NULL,10251,1,'09:00','10:00',0);











insert into schedules values(NULL,10238,1,'10:00','11:00',0);
insert into schedules values(NULL,10239,1,'10:00','11:00',0);
insert into schedules values(NULL,10241,1,'10:00','11:00',0);
insert into schedules values(NULL,10242,1,'10:00','11:00',0);
insert into schedules values(NULL,10244,1,'10:00','11:00',0);
insert into schedules values(NULL,10245,1,'10:00','11:00',0);
insert into schedules values(NULL,10247,1,'10:00','11:00',0);
insert into schedules values(NULL,10249,1,'10:00','11:00',0);
insert into schedules values(NULL,10251,1,'10:00','11:00',0);











insert into schedules values(NULL,10238,1,'11:00','12:00',0);
insert into schedules values(NULL,10239,1,'11:00','12:00',0);
insert into schedules values(NULL,10241,1,'11:00','12:00',0);
insert into schedules values(NULL,10242,1,'11:00','12:00',0);
insert into schedules values(NULL,10244,1,'11:00','12:00',0);
insert into schedules values(NULL,10245,1,'11:00','12:00',0);
insert into schedules values(NULL,10247,1,'11:00','12:00',0);
insert into schedules values(NULL,10249,1,'11:00','12:00',0);
insert into schedules values(NULL,10251,1,'11:00','12:00',0);











insert into schedules values(NULL,10238,1,'12:00','13:00',0);
insert into schedules values(NULL,10239,1,'12:00','13:00',0);
insert into schedules values(NULL,10241,1,'12:00','13:00',0);
insert into schedules values(NULL,10242,1,'12:00','13:00',0);
insert into schedules values(NULL,10244,1,'12:00','13:00',0);
insert into schedules values(NULL,10245,1,'12:00','13:00',0);
insert into schedules values(NULL,10247,1,'12:00','13:00',0);
insert into schedules values(NULL,10249,1,'12:00','13:00',0);
insert into schedules values(NULL,10251,1,'12:00','13:00',0);











insert into schedules values(NULL,10238,1,'13:00','14:00',0);
insert into schedules values(NULL,10239,1,'13:00','14:00',0);
insert into schedules values(NULL,10241,1,'13:00','14:00',0);
insert into schedules values(NULL,10242,1,'13:00','14:00',0);
insert into schedules values(NULL,10244,1,'13:00','14:00',0);
insert into schedules values(NULL,10245,1,'13:00','14:00',0);
insert into schedules values(NULL,10247,1,'13:00','14:00',0);
insert into schedules values(NULL,10249,1,'13:00','14:00',0);
insert into schedules values(NULL,10251,1,'13:00','14:00',0);











insert into schedules values(NULL,10238,1,'14:00','15:00',0);
insert into schedules values(NULL,10239,1,'14:00','15:00',0);
insert into schedules values(NULL,10241,1,'14:00','15:00',0);
insert into schedules values(NULL,10242,1,'14:00','15:00',0);
insert into schedules values(NULL,10244,1,'14:00','15:00',0);
insert into schedules values(NULL,10245,1,'14:00','15:00',0);
insert into schedules values(NULL,10247,1,'14:00','15:00',0);
insert into schedules values(NULL,10249,1,'14:00','15:00',0);
insert into schedules values(NULL,10251,1,'14:00','15:00',0);











insert into schedules values(NULL,10238,1,'15:00','16:00',0);
insert into schedules values(NULL,10239,1,'15:00','16:00',0);
insert into schedules values(NULL,10241,1,'15:00','16:00',0);
insert into schedules values(NULL,10242,1,'15:00','16:00',0);
insert into schedules values(NULL,10244,1,'15:00','16:00',0);
insert into schedules values(NULL,10245,1,'15:00','16:00',0);
insert into schedules values(NULL,10247,1,'15:00','16:00',0);
insert into schedules values(NULL,10249,1,'15:00','16:00',0);
insert into schedules values(NULL,10251,1,'15:00','16:00',0);











insert into schedules values(NULL,10238,1,'16:00','17:00',0);
insert into schedules values(NULL,10239,1,'16:00','17:00',0);
insert into schedules values(NULL,10241,1,'16:00','17:00',0);
insert into schedules values(NULL,10242,1,'16:00','17:00',0);
insert into schedules values(NULL,10244,1,'16:00','17:00',0);
insert into schedules values(NULL,10245,1,'16:00','17:00',0);
insert into schedules values(NULL,10247,1,'16:00','17:00',0);
insert into schedules values(NULL,10249,1,'16:00','17:00',0);
insert into schedules values(NULL,10251,1,'16:00','17:00',0);











insert into schedules values(NULL,10238,1,'17:00','18:00',0);
insert into schedules values(NULL,10239,1,'17:00','18:00',0);
insert into schedules values(NULL,10241,1,'17:00','18:00',0);
insert into schedules values(NULL,10242,1,'17:00','18:00',0);
insert into schedules values(NULL,10244,1,'17:00','18:00',0);
insert into schedules values(NULL,10245,1,'17:00','18:00',0);
insert into schedules values(NULL,10247,1,'17:00','18:00',0);
insert into schedules values(NULL,10249,1,'17:00','18:00',0);
insert into schedules values(NULL,10251,1,'17:00','18:00',0);











insert into schedules values(NULL,10238,1,'18:00','19:00',0);
insert into schedules values(NULL,10239,1,'18:00','19:00',0);
insert into schedules values(NULL,10241,1,'18:00','19:00',0);
insert into schedules values(NULL,10242,1,'18:00','19:00',0);
insert into schedules values(NULL,10244,1,'18:00','19:00',0);
insert into schedules values(NULL,10245,1,'18:00','19:00',0);
insert into schedules values(NULL,10247,1,'18:00','19:00',0);
insert into schedules values(NULL,10249,1,'18:00','19:00',0);
insert into schedules values(NULL,10251,1,'18:00','19:00',0);











insert into schedules values(NULL,10238,1,'19:00','20:00',0);
insert into schedules values(NULL,10239,1,'19:00','20:00',0);
insert into schedules values(NULL,10241,1,'19:00','20:00',0);
insert into schedules values(NULL,10242,1,'19:00','20:00',0);
insert into schedules values(NULL,10244,1,'19:00','20:00',0);
insert into schedules values(NULL,10245,1,'19:00','20:00',0);
insert into schedules values(NULL,10247,1,'19:00','20:00',0);
insert into schedules values(NULL,10249,1,'19:00','20:00',0);
insert into schedules values(NULL,10251,1,'19:00','20:00',0);

insert into schedules values(NULL,10255,1,'19:00','20:00',0);

insert into schedules values(NULL,10257,1,'19:00','20:00',0);
insert into schedules values(NULL,10258,1,'19:00','20:00',0);
insert into schedules values(NULL,15201,1,'19:00','20:00',0);

